// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Bundle is the predicate function for bundle builders.
type Bundle func(*sql.Selector)

// Pokemon is the predicate function for pokemon builders.
type Pokemon func(*sql.Selector)
