// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/FlagBrew/local-gpss/internal/database/ent/bundle"
)

// Bundle is the model entity for the Bundle schema.
type Bundle struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// UploadDatetime holds the value of the "upload_datetime" field.
	UploadDatetime time.Time `json:"upload_datetime,omitempty"`
	// DownloadCode holds the value of the "download_code" field.
	DownloadCode string `json:"download_code,omitempty"`
	// DownloadCount holds the value of the "download_count" field.
	DownloadCount int `json:"download_count,omitempty"`
	// Legal holds the value of the "legal" field.
	Legal bool `json:"legal,omitempty"`
	// MinGen holds the value of the "min_gen" field.
	MinGen string `json:"min_gen,omitempty"`
	// MaxGen holds the value of the "max_gen" field.
	MaxGen string `json:"max_gen,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the BundleQuery when eager-loading is set.
	Edges        BundleEdges `json:"edges"`
	selectValues sql.SelectValues
}

// BundleEdges holds the relations/edges for other nodes in the graph.
type BundleEdges struct {
	// Pokemons holds the value of the pokemons edge.
	Pokemons []*Pokemon `json:"pokemons,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// PokemonsOrErr returns the Pokemons value or an error if the edge
// was not loaded in eager-loading.
func (e BundleEdges) PokemonsOrErr() ([]*Pokemon, error) {
	if e.loadedTypes[0] {
		return e.Pokemons, nil
	}
	return nil, &NotLoadedError{edge: "pokemons"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Bundle) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case bundle.FieldLegal:
			values[i] = new(sql.NullBool)
		case bundle.FieldID, bundle.FieldDownloadCount:
			values[i] = new(sql.NullInt64)
		case bundle.FieldDownloadCode, bundle.FieldMinGen, bundle.FieldMaxGen:
			values[i] = new(sql.NullString)
		case bundle.FieldUploadDatetime:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Bundle fields.
func (_m *Bundle) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case bundle.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case bundle.FieldUploadDatetime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field upload_datetime", values[i])
			} else if value.Valid {
				_m.UploadDatetime = value.Time
			}
		case bundle.FieldDownloadCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field download_code", values[i])
			} else if value.Valid {
				_m.DownloadCode = value.String
			}
		case bundle.FieldDownloadCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field download_count", values[i])
			} else if value.Valid {
				_m.DownloadCount = int(value.Int64)
			}
		case bundle.FieldLegal:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field legal", values[i])
			} else if value.Valid {
				_m.Legal = value.Bool
			}
		case bundle.FieldMinGen:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field min_gen", values[i])
			} else if value.Valid {
				_m.MinGen = value.String
			}
		case bundle.FieldMaxGen:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field max_gen", values[i])
			} else if value.Valid {
				_m.MaxGen = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Bundle.
// This includes values selected through modifiers, order, etc.
func (_m *Bundle) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPokemons queries the "pokemons" edge of the Bundle entity.
func (_m *Bundle) QueryPokemons() *PokemonQuery {
	return NewBundleClient(_m.config).QueryPokemons(_m)
}

// Update returns a builder for updating this Bundle.
// Note that you need to call Bundle.Unwrap() before calling this method if this Bundle
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Bundle) Update() *BundleUpdateOne {
	return NewBundleClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Bundle entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Bundle) Unwrap() *Bundle {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Bundle is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Bundle) String() string {
	var builder strings.Builder
	builder.WriteString("Bundle(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("upload_datetime=")
	builder.WriteString(_m.UploadDatetime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("download_code=")
	builder.WriteString(_m.DownloadCode)
	builder.WriteString(", ")
	builder.WriteString("download_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.DownloadCount))
	builder.WriteString(", ")
	builder.WriteString("legal=")
	builder.WriteString(fmt.Sprintf("%v", _m.Legal))
	builder.WriteString(", ")
	builder.WriteString("min_gen=")
	builder.WriteString(_m.MinGen)
	builder.WriteString(", ")
	builder.WriteString("max_gen=")
	builder.WriteString(_m.MaxGen)
	builder.WriteByte(')')
	return builder.String()
}

// Bundles is a parsable slice of Bundle.
type Bundles []*Bundle
