// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/FlagBrew/local-gpss/internal/database/ent/bundle"
	"github.com/FlagBrew/local-gpss/internal/database/ent/pokemon"
)

// BundleCreate is the builder for creating a Bundle entity.
type BundleCreate struct {
	config
	mutation *BundleMutation
	hooks    []Hook
}

// SetUploadDatetime sets the "upload_datetime" field.
func (_c *BundleCreate) SetUploadDatetime(v time.Time) *BundleCreate {
	_c.mutation.SetUploadDatetime(v)
	return _c
}

// SetDownloadCode sets the "download_code" field.
func (_c *BundleCreate) SetDownloadCode(v string) *BundleCreate {
	_c.mutation.SetDownloadCode(v)
	return _c
}

// SetDownloadCount sets the "download_count" field.
func (_c *BundleCreate) SetDownloadCount(v int) *BundleCreate {
	_c.mutation.SetDownloadCount(v)
	return _c
}

// SetNillableDownloadCount sets the "download_count" field if the given value is not nil.
func (_c *BundleCreate) SetNillableDownloadCount(v *int) *BundleCreate {
	if v != nil {
		_c.SetDownloadCount(*v)
	}
	return _c
}

// SetLegal sets the "legal" field.
func (_c *BundleCreate) SetLegal(v bool) *BundleCreate {
	_c.mutation.SetLegal(v)
	return _c
}

// SetMinGen sets the "min_gen" field.
func (_c *BundleCreate) SetMinGen(v string) *BundleCreate {
	_c.mutation.SetMinGen(v)
	return _c
}

// SetMaxGen sets the "max_gen" field.
func (_c *BundleCreate) SetMaxGen(v string) *BundleCreate {
	_c.mutation.SetMaxGen(v)
	return _c
}

// AddPokemonIDs adds the "pokemons" edge to the Pokemon entity by IDs.
func (_c *BundleCreate) AddPokemonIDs(ids ...int) *BundleCreate {
	_c.mutation.AddPokemonIDs(ids...)
	return _c
}

// AddPokemons adds the "pokemons" edges to the Pokemon entity.
func (_c *BundleCreate) AddPokemons(v ...*Pokemon) *BundleCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddPokemonIDs(ids...)
}

// Mutation returns the BundleMutation object of the builder.
func (_c *BundleCreate) Mutation() *BundleMutation {
	return _c.mutation
}

// Save creates the Bundle in the database.
func (_c *BundleCreate) Save(ctx context.Context) (*Bundle, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *BundleCreate) SaveX(ctx context.Context) *Bundle {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BundleCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BundleCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *BundleCreate) defaults() {
	if _, ok := _c.mutation.DownloadCount(); !ok {
		v := bundle.DefaultDownloadCount
		_c.mutation.SetDownloadCount(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *BundleCreate) check() error {
	if _, ok := _c.mutation.UploadDatetime(); !ok {
		return &ValidationError{Name: "upload_datetime", err: errors.New(`ent: missing required field "Bundle.upload_datetime"`)}
	}
	if _, ok := _c.mutation.DownloadCode(); !ok {
		return &ValidationError{Name: "download_code", err: errors.New(`ent: missing required field "Bundle.download_code"`)}
	}
	if _, ok := _c.mutation.DownloadCount(); !ok {
		return &ValidationError{Name: "download_count", err: errors.New(`ent: missing required field "Bundle.download_count"`)}
	}
	if _, ok := _c.mutation.Legal(); !ok {
		return &ValidationError{Name: "legal", err: errors.New(`ent: missing required field "Bundle.legal"`)}
	}
	if _, ok := _c.mutation.MinGen(); !ok {
		return &ValidationError{Name: "min_gen", err: errors.New(`ent: missing required field "Bundle.min_gen"`)}
	}
	if _, ok := _c.mutation.MaxGen(); !ok {
		return &ValidationError{Name: "max_gen", err: errors.New(`ent: missing required field "Bundle.max_gen"`)}
	}
	return nil
}

func (_c *BundleCreate) sqlSave(ctx context.Context) (*Bundle, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *BundleCreate) createSpec() (*Bundle, *sqlgraph.CreateSpec) {
	var (
		_node = &Bundle{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(bundle.Table, sqlgraph.NewFieldSpec(bundle.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.UploadDatetime(); ok {
		_spec.SetField(bundle.FieldUploadDatetime, field.TypeTime, value)
		_node.UploadDatetime = value
	}
	if value, ok := _c.mutation.DownloadCode(); ok {
		_spec.SetField(bundle.FieldDownloadCode, field.TypeString, value)
		_node.DownloadCode = value
	}
	if value, ok := _c.mutation.DownloadCount(); ok {
		_spec.SetField(bundle.FieldDownloadCount, field.TypeInt, value)
		_node.DownloadCount = value
	}
	if value, ok := _c.mutation.Legal(); ok {
		_spec.SetField(bundle.FieldLegal, field.TypeBool, value)
		_node.Legal = value
	}
	if value, ok := _c.mutation.MinGen(); ok {
		_spec.SetField(bundle.FieldMinGen, field.TypeString, value)
		_node.MinGen = value
	}
	if value, ok := _c.mutation.MaxGen(); ok {
		_spec.SetField(bundle.FieldMaxGen, field.TypeString, value)
		_node.MaxGen = value
	}
	if nodes := _c.mutation.PokemonsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   bundle.PokemonsTable,
			Columns: bundle.PokemonsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pokemon.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// BundleCreateBulk is the builder for creating many Bundle entities in bulk.
type BundleCreateBulk struct {
	config
	err      error
	builders []*BundleCreate
}

// Save creates the Bundle entities in the database.
func (_c *BundleCreateBulk) Save(ctx context.Context) ([]*Bundle, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Bundle, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BundleMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *BundleCreateBulk) SaveX(ctx context.Context) []*Bundle {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BundleCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BundleCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
