// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/FlagBrew/local-gpss/internal/database/ent/bundle"
	"github.com/FlagBrew/local-gpss/internal/database/ent/pokemon"
	"github.com/FlagBrew/local-gpss/internal/database/ent/predicate"
)

// BundleUpdate is the builder for updating Bundle entities.
type BundleUpdate struct {
	config
	hooks    []Hook
	mutation *BundleMutation
}

// Where appends a list predicates to the BundleUpdate builder.
func (_u *BundleUpdate) Where(ps ...predicate.Bundle) *BundleUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUploadDatetime sets the "upload_datetime" field.
func (_u *BundleUpdate) SetUploadDatetime(v time.Time) *BundleUpdate {
	_u.mutation.SetUploadDatetime(v)
	return _u
}

// SetNillableUploadDatetime sets the "upload_datetime" field if the given value is not nil.
func (_u *BundleUpdate) SetNillableUploadDatetime(v *time.Time) *BundleUpdate {
	if v != nil {
		_u.SetUploadDatetime(*v)
	}
	return _u
}

// SetDownloadCode sets the "download_code" field.
func (_u *BundleUpdate) SetDownloadCode(v string) *BundleUpdate {
	_u.mutation.SetDownloadCode(v)
	return _u
}

// SetNillableDownloadCode sets the "download_code" field if the given value is not nil.
func (_u *BundleUpdate) SetNillableDownloadCode(v *string) *BundleUpdate {
	if v != nil {
		_u.SetDownloadCode(*v)
	}
	return _u
}

// SetDownloadCount sets the "download_count" field.
func (_u *BundleUpdate) SetDownloadCount(v int) *BundleUpdate {
	_u.mutation.ResetDownloadCount()
	_u.mutation.SetDownloadCount(v)
	return _u
}

// SetNillableDownloadCount sets the "download_count" field if the given value is not nil.
func (_u *BundleUpdate) SetNillableDownloadCount(v *int) *BundleUpdate {
	if v != nil {
		_u.SetDownloadCount(*v)
	}
	return _u
}

// AddDownloadCount adds value to the "download_count" field.
func (_u *BundleUpdate) AddDownloadCount(v int) *BundleUpdate {
	_u.mutation.AddDownloadCount(v)
	return _u
}

// SetLegal sets the "legal" field.
func (_u *BundleUpdate) SetLegal(v bool) *BundleUpdate {
	_u.mutation.SetLegal(v)
	return _u
}

// SetNillableLegal sets the "legal" field if the given value is not nil.
func (_u *BundleUpdate) SetNillableLegal(v *bool) *BundleUpdate {
	if v != nil {
		_u.SetLegal(*v)
	}
	return _u
}

// SetMinGen sets the "min_gen" field.
func (_u *BundleUpdate) SetMinGen(v string) *BundleUpdate {
	_u.mutation.SetMinGen(v)
	return _u
}

// SetNillableMinGen sets the "min_gen" field if the given value is not nil.
func (_u *BundleUpdate) SetNillableMinGen(v *string) *BundleUpdate {
	if v != nil {
		_u.SetMinGen(*v)
	}
	return _u
}

// SetMaxGen sets the "max_gen" field.
func (_u *BundleUpdate) SetMaxGen(v string) *BundleUpdate {
	_u.mutation.SetMaxGen(v)
	return _u
}

// SetNillableMaxGen sets the "max_gen" field if the given value is not nil.
func (_u *BundleUpdate) SetNillableMaxGen(v *string) *BundleUpdate {
	if v != nil {
		_u.SetMaxGen(*v)
	}
	return _u
}

// AddPokemonIDs adds the "pokemons" edge to the Pokemon entity by IDs.
func (_u *BundleUpdate) AddPokemonIDs(ids ...int) *BundleUpdate {
	_u.mutation.AddPokemonIDs(ids...)
	return _u
}

// AddPokemons adds the "pokemons" edges to the Pokemon entity.
func (_u *BundleUpdate) AddPokemons(v ...*Pokemon) *BundleUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPokemonIDs(ids...)
}

// Mutation returns the BundleMutation object of the builder.
func (_u *BundleUpdate) Mutation() *BundleMutation {
	return _u.mutation
}

// ClearPokemons clears all "pokemons" edges to the Pokemon entity.
func (_u *BundleUpdate) ClearPokemons() *BundleUpdate {
	_u.mutation.ClearPokemons()
	return _u
}

// RemovePokemonIDs removes the "pokemons" edge to Pokemon entities by IDs.
func (_u *BundleUpdate) RemovePokemonIDs(ids ...int) *BundleUpdate {
	_u.mutation.RemovePokemonIDs(ids...)
	return _u
}

// RemovePokemons removes "pokemons" edges to Pokemon entities.
func (_u *BundleUpdate) RemovePokemons(v ...*Pokemon) *BundleUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePokemonIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BundleUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BundleUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BundleUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BundleUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *BundleUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(bundle.Table, bundle.Columns, sqlgraph.NewFieldSpec(bundle.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UploadDatetime(); ok {
		_spec.SetField(bundle.FieldUploadDatetime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DownloadCode(); ok {
		_spec.SetField(bundle.FieldDownloadCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.DownloadCount(); ok {
		_spec.SetField(bundle.FieldDownloadCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDownloadCount(); ok {
		_spec.AddField(bundle.FieldDownloadCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Legal(); ok {
		_spec.SetField(bundle.FieldLegal, field.TypeBool, value)
	}
	if value, ok := _u.mutation.MinGen(); ok {
		_spec.SetField(bundle.FieldMinGen, field.TypeString, value)
	}
	if value, ok := _u.mutation.MaxGen(); ok {
		_spec.SetField(bundle.FieldMaxGen, field.TypeString, value)
	}
	if _u.mutation.PokemonsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   bundle.PokemonsTable,
			Columns: bundle.PokemonsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pokemon.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPokemonsIDs(); len(nodes) > 0 && !_u.mutation.PokemonsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   bundle.PokemonsTable,
			Columns: bundle.PokemonsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pokemon.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PokemonsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   bundle.PokemonsTable,
			Columns: bundle.PokemonsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pokemon.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{bundle.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BundleUpdateOne is the builder for updating a single Bundle entity.
type BundleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BundleMutation
}

// SetUploadDatetime sets the "upload_datetime" field.
func (_u *BundleUpdateOne) SetUploadDatetime(v time.Time) *BundleUpdateOne {
	_u.mutation.SetUploadDatetime(v)
	return _u
}

// SetNillableUploadDatetime sets the "upload_datetime" field if the given value is not nil.
func (_u *BundleUpdateOne) SetNillableUploadDatetime(v *time.Time) *BundleUpdateOne {
	if v != nil {
		_u.SetUploadDatetime(*v)
	}
	return _u
}

// SetDownloadCode sets the "download_code" field.
func (_u *BundleUpdateOne) SetDownloadCode(v string) *BundleUpdateOne {
	_u.mutation.SetDownloadCode(v)
	return _u
}

// SetNillableDownloadCode sets the "download_code" field if the given value is not nil.
func (_u *BundleUpdateOne) SetNillableDownloadCode(v *string) *BundleUpdateOne {
	if v != nil {
		_u.SetDownloadCode(*v)
	}
	return _u
}

// SetDownloadCount sets the "download_count" field.
func (_u *BundleUpdateOne) SetDownloadCount(v int) *BundleUpdateOne {
	_u.mutation.ResetDownloadCount()
	_u.mutation.SetDownloadCount(v)
	return _u
}

// SetNillableDownloadCount sets the "download_count" field if the given value is not nil.
func (_u *BundleUpdateOne) SetNillableDownloadCount(v *int) *BundleUpdateOne {
	if v != nil {
		_u.SetDownloadCount(*v)
	}
	return _u
}

// AddDownloadCount adds value to the "download_count" field.
func (_u *BundleUpdateOne) AddDownloadCount(v int) *BundleUpdateOne {
	_u.mutation.AddDownloadCount(v)
	return _u
}

// SetLegal sets the "legal" field.
func (_u *BundleUpdateOne) SetLegal(v bool) *BundleUpdateOne {
	_u.mutation.SetLegal(v)
	return _u
}

// SetNillableLegal sets the "legal" field if the given value is not nil.
func (_u *BundleUpdateOne) SetNillableLegal(v *bool) *BundleUpdateOne {
	if v != nil {
		_u.SetLegal(*v)
	}
	return _u
}

// SetMinGen sets the "min_gen" field.
func (_u *BundleUpdateOne) SetMinGen(v string) *BundleUpdateOne {
	_u.mutation.SetMinGen(v)
	return _u
}

// SetNillableMinGen sets the "min_gen" field if the given value is not nil.
func (_u *BundleUpdateOne) SetNillableMinGen(v *string) *BundleUpdateOne {
	if v != nil {
		_u.SetMinGen(*v)
	}
	return _u
}

// SetMaxGen sets the "max_gen" field.
func (_u *BundleUpdateOne) SetMaxGen(v string) *BundleUpdateOne {
	_u.mutation.SetMaxGen(v)
	return _u
}

// SetNillableMaxGen sets the "max_gen" field if the given value is not nil.
func (_u *BundleUpdateOne) SetNillableMaxGen(v *string) *BundleUpdateOne {
	if v != nil {
		_u.SetMaxGen(*v)
	}
	return _u
}

// AddPokemonIDs adds the "pokemons" edge to the Pokemon entity by IDs.
func (_u *BundleUpdateOne) AddPokemonIDs(ids ...int) *BundleUpdateOne {
	_u.mutation.AddPokemonIDs(ids...)
	return _u
}

// AddPokemons adds the "pokemons" edges to the Pokemon entity.
func (_u *BundleUpdateOne) AddPokemons(v ...*Pokemon) *BundleUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPokemonIDs(ids...)
}

// Mutation returns the BundleMutation object of the builder.
func (_u *BundleUpdateOne) Mutation() *BundleMutation {
	return _u.mutation
}

// ClearPokemons clears all "pokemons" edges to the Pokemon entity.
func (_u *BundleUpdateOne) ClearPokemons() *BundleUpdateOne {
	_u.mutation.ClearPokemons()
	return _u
}

// RemovePokemonIDs removes the "pokemons" edge to Pokemon entities by IDs.
func (_u *BundleUpdateOne) RemovePokemonIDs(ids ...int) *BundleUpdateOne {
	_u.mutation.RemovePokemonIDs(ids...)
	return _u
}

// RemovePokemons removes "pokemons" edges to Pokemon entities.
func (_u *BundleUpdateOne) RemovePokemons(v ...*Pokemon) *BundleUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePokemonIDs(ids...)
}

// Where appends a list predicates to the BundleUpdate builder.
func (_u *BundleUpdateOne) Where(ps ...predicate.Bundle) *BundleUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BundleUpdateOne) Select(field string, fields ...string) *BundleUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Bundle entity.
func (_u *BundleUpdateOne) Save(ctx context.Context) (*Bundle, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BundleUpdateOne) SaveX(ctx context.Context) *Bundle {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BundleUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BundleUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *BundleUpdateOne) sqlSave(ctx context.Context) (_node *Bundle, err error) {
	_spec := sqlgraph.NewUpdateSpec(bundle.Table, bundle.Columns, sqlgraph.NewFieldSpec(bundle.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Bundle.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, bundle.FieldID)
		for _, f := range fields {
			if !bundle.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != bundle.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UploadDatetime(); ok {
		_spec.SetField(bundle.FieldUploadDatetime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DownloadCode(); ok {
		_spec.SetField(bundle.FieldDownloadCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.DownloadCount(); ok {
		_spec.SetField(bundle.FieldDownloadCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDownloadCount(); ok {
		_spec.AddField(bundle.FieldDownloadCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Legal(); ok {
		_spec.SetField(bundle.FieldLegal, field.TypeBool, value)
	}
	if value, ok := _u.mutation.MinGen(); ok {
		_spec.SetField(bundle.FieldMinGen, field.TypeString, value)
	}
	if value, ok := _u.mutation.MaxGen(); ok {
		_spec.SetField(bundle.FieldMaxGen, field.TypeString, value)
	}
	if _u.mutation.PokemonsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   bundle.PokemonsTable,
			Columns: bundle.PokemonsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pokemon.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPokemonsIDs(); len(nodes) > 0 && !_u.mutation.PokemonsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   bundle.PokemonsTable,
			Columns: bundle.PokemonsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pokemon.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PokemonsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   bundle.PokemonsTable,
			Columns: bundle.PokemonsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pokemon.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Bundle{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{bundle.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
