// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/FlagBrew/local-gpss/internal/database/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/FlagBrew/local-gpss/internal/database/ent/bundle"
	"github.com/FlagBrew/local-gpss/internal/database/ent/pokemon"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Bundle is the client for interacting with the Bundle builders.
	Bundle *BundleClient
	// Pokemon is the client for interacting with the Pokemon builders.
	Pokemon *PokemonClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Bundle = NewBundleClient(c.config)
	c.Pokemon = NewPokemonClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:     ctx,
		config:  cfg,
		Bundle:  NewBundleClient(cfg),
		Pokemon: NewPokemonClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:     ctx,
		config:  cfg,
		Bundle:  NewBundleClient(cfg),
		Pokemon: NewPokemonClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Bundle.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Bundle.Use(hooks...)
	c.Pokemon.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.Bundle.Intercept(interceptors...)
	c.Pokemon.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *BundleMutation:
		return c.Bundle.mutate(ctx, m)
	case *PokemonMutation:
		return c.Pokemon.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// BundleClient is a client for the Bundle schema.
type BundleClient struct {
	config
}

// NewBundleClient returns a client for the Bundle from the given config.
func NewBundleClient(c config) *BundleClient {
	return &BundleClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `bundle.Hooks(f(g(h())))`.
func (c *BundleClient) Use(hooks ...Hook) {
	c.hooks.Bundle = append(c.hooks.Bundle, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `bundle.Intercept(f(g(h())))`.
func (c *BundleClient) Intercept(interceptors ...Interceptor) {
	c.inters.Bundle = append(c.inters.Bundle, interceptors...)
}

// Create returns a builder for creating a Bundle entity.
func (c *BundleClient) Create() *BundleCreate {
	mutation := newBundleMutation(c.config, OpCreate)
	return &BundleCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Bundle entities.
func (c *BundleClient) CreateBulk(builders ...*BundleCreate) *BundleCreateBulk {
	return &BundleCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *BundleClient) MapCreateBulk(slice any, setFunc func(*BundleCreate, int)) *BundleCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &BundleCreateBulk{err: fmt.Errorf("calling to BundleClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*BundleCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &BundleCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Bundle.
func (c *BundleClient) Update() *BundleUpdate {
	mutation := newBundleMutation(c.config, OpUpdate)
	return &BundleUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *BundleClient) UpdateOne(_m *Bundle) *BundleUpdateOne {
	mutation := newBundleMutation(c.config, OpUpdateOne, withBundle(_m))
	return &BundleUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *BundleClient) UpdateOneID(id int) *BundleUpdateOne {
	mutation := newBundleMutation(c.config, OpUpdateOne, withBundleID(id))
	return &BundleUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Bundle.
func (c *BundleClient) Delete() *BundleDelete {
	mutation := newBundleMutation(c.config, OpDelete)
	return &BundleDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *BundleClient) DeleteOne(_m *Bundle) *BundleDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *BundleClient) DeleteOneID(id int) *BundleDeleteOne {
	builder := c.Delete().Where(bundle.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &BundleDeleteOne{builder}
}

// Query returns a query builder for Bundle.
func (c *BundleClient) Query() *BundleQuery {
	return &BundleQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeBundle},
		inters: c.Interceptors(),
	}
}

// Get returns a Bundle entity by its id.
func (c *BundleClient) Get(ctx context.Context, id int) (*Bundle, error) {
	return c.Query().Where(bundle.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *BundleClient) GetX(ctx context.Context, id int) *Bundle {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryPokemons queries the pokemons edge of a Bundle.
func (c *BundleClient) QueryPokemons(_m *Bundle) *PokemonQuery {
	query := (&PokemonClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(bundle.Table, bundle.FieldID, id),
			sqlgraph.To(pokemon.Table, pokemon.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, bundle.PokemonsTable, bundle.PokemonsPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *BundleClient) Hooks() []Hook {
	return c.hooks.Bundle
}

// Interceptors returns the client interceptors.
func (c *BundleClient) Interceptors() []Interceptor {
	return c.inters.Bundle
}

func (c *BundleClient) mutate(ctx context.Context, m *BundleMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&BundleCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&BundleUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&BundleUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&BundleDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Bundle mutation op: %q", m.Op())
	}
}

// PokemonClient is a client for the Pokemon schema.
type PokemonClient struct {
	config
}

// NewPokemonClient returns a client for the Pokemon from the given config.
func NewPokemonClient(c config) *PokemonClient {
	return &PokemonClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `pokemon.Hooks(f(g(h())))`.
func (c *PokemonClient) Use(hooks ...Hook) {
	c.hooks.Pokemon = append(c.hooks.Pokemon, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `pokemon.Intercept(f(g(h())))`.
func (c *PokemonClient) Intercept(interceptors ...Interceptor) {
	c.inters.Pokemon = append(c.inters.Pokemon, interceptors...)
}

// Create returns a builder for creating a Pokemon entity.
func (c *PokemonClient) Create() *PokemonCreate {
	mutation := newPokemonMutation(c.config, OpCreate)
	return &PokemonCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Pokemon entities.
func (c *PokemonClient) CreateBulk(builders ...*PokemonCreate) *PokemonCreateBulk {
	return &PokemonCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *PokemonClient) MapCreateBulk(slice any, setFunc func(*PokemonCreate, int)) *PokemonCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &PokemonCreateBulk{err: fmt.Errorf("calling to PokemonClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*PokemonCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &PokemonCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Pokemon.
func (c *PokemonClient) Update() *PokemonUpdate {
	mutation := newPokemonMutation(c.config, OpUpdate)
	return &PokemonUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *PokemonClient) UpdateOne(_m *Pokemon) *PokemonUpdateOne {
	mutation := newPokemonMutation(c.config, OpUpdateOne, withPokemon(_m))
	return &PokemonUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *PokemonClient) UpdateOneID(id int) *PokemonUpdateOne {
	mutation := newPokemonMutation(c.config, OpUpdateOne, withPokemonID(id))
	return &PokemonUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Pokemon.
func (c *PokemonClient) Delete() *PokemonDelete {
	mutation := newPokemonMutation(c.config, OpDelete)
	return &PokemonDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *PokemonClient) DeleteOne(_m *Pokemon) *PokemonDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *PokemonClient) DeleteOneID(id int) *PokemonDeleteOne {
	builder := c.Delete().Where(pokemon.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &PokemonDeleteOne{builder}
}

// Query returns a query builder for Pokemon.
func (c *PokemonClient) Query() *PokemonQuery {
	return &PokemonQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypePokemon},
		inters: c.Interceptors(),
	}
}

// Get returns a Pokemon entity by its id.
func (c *PokemonClient) Get(ctx context.Context, id int) (*Pokemon, error) {
	return c.Query().Where(pokemon.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *PokemonClient) GetX(ctx context.Context, id int) *Pokemon {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryBundles queries the bundles edge of a Pokemon.
func (c *PokemonClient) QueryBundles(_m *Pokemon) *BundleQuery {
	query := (&BundleClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(pokemon.Table, pokemon.FieldID, id),
			sqlgraph.To(bundle.Table, bundle.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, pokemon.BundlesTable, pokemon.BundlesPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *PokemonClient) Hooks() []Hook {
	return c.hooks.Pokemon
}

// Interceptors returns the client interceptors.
func (c *PokemonClient) Interceptors() []Interceptor {
	return c.inters.Pokemon
}

func (c *PokemonClient) mutate(ctx context.Context, m *PokemonMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&PokemonCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&PokemonUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&PokemonUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&PokemonDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Pokemon mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		Bundle, Pokemon []ent.Hook
	}
	inters struct {
		Bundle, Pokemon []ent.Interceptor
	}
)
