// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/FlagBrew/local-gpss/internal/database/ent/bundle"
	"github.com/FlagBrew/local-gpss/internal/database/ent/pokemon"
	"github.com/FlagBrew/local-gpss/internal/database/ent/predicate"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeBundle  = "Bundle"
	TypePokemon = "Pokemon"
)

// BundleMutation represents an operation that mutates the Bundle nodes in the graph.
type BundleMutation struct {
	config
	op                Op
	typ               string
	id                *int
	upload_datetime   *time.Time
	download_code     *string
	download_count    *int
	adddownload_count *int
	legal             *bool
	min_gen           *string
	max_gen           *string
	clearedFields     map[string]struct{}
	pokemons          map[int]struct{}
	removedpokemons   map[int]struct{}
	clearedpokemons   bool
	done              bool
	oldValue          func(context.Context) (*Bundle, error)
	predicates        []predicate.Bundle
}

var _ ent.Mutation = (*BundleMutation)(nil)

// bundleOption allows management of the mutation configuration using functional options.
type bundleOption func(*BundleMutation)

// newBundleMutation creates new mutation for the Bundle entity.
func newBundleMutation(c config, op Op, opts ...bundleOption) *BundleMutation {
	m := &BundleMutation{
		config:        c,
		op:            op,
		typ:           TypeBundle,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withBundleID sets the ID field of the mutation.
func withBundleID(id int) bundleOption {
	return func(m *BundleMutation) {
		var (
			err   error
			once  sync.Once
			value *Bundle
		)
		m.oldValue = func(ctx context.Context) (*Bundle, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Bundle.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withBundle sets the old Bundle of the mutation.
func withBundle(node *Bundle) bundleOption {
	return func(m *BundleMutation) {
		m.oldValue = func(context.Context) (*Bundle, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m BundleMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m BundleMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *BundleMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *BundleMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Bundle.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetUploadDatetime sets the "upload_datetime" field.
func (m *BundleMutation) SetUploadDatetime(t time.Time) {
	m.upload_datetime = &t
}

// UploadDatetime returns the value of the "upload_datetime" field in the mutation.
func (m *BundleMutation) UploadDatetime() (r time.Time, exists bool) {
	v := m.upload_datetime
	if v == nil {
		return
	}
	return *v, true
}

// OldUploadDatetime returns the old "upload_datetime" field's value of the Bundle entity.
// If the Bundle object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *BundleMutation) OldUploadDatetime(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUploadDatetime is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUploadDatetime requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUploadDatetime: %w", err)
	}
	return oldValue.UploadDatetime, nil
}

// ResetUploadDatetime resets all changes to the "upload_datetime" field.
func (m *BundleMutation) ResetUploadDatetime() {
	m.upload_datetime = nil
}

// SetDownloadCode sets the "download_code" field.
func (m *BundleMutation) SetDownloadCode(s string) {
	m.download_code = &s
}

// DownloadCode returns the value of the "download_code" field in the mutation.
func (m *BundleMutation) DownloadCode() (r string, exists bool) {
	v := m.download_code
	if v == nil {
		return
	}
	return *v, true
}

// OldDownloadCode returns the old "download_code" field's value of the Bundle entity.
// If the Bundle object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *BundleMutation) OldDownloadCode(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDownloadCode is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDownloadCode requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDownloadCode: %w", err)
	}
	return oldValue.DownloadCode, nil
}

// ResetDownloadCode resets all changes to the "download_code" field.
func (m *BundleMutation) ResetDownloadCode() {
	m.download_code = nil
}

// SetDownloadCount sets the "download_count" field.
func (m *BundleMutation) SetDownloadCount(i int) {
	m.download_count = &i
	m.adddownload_count = nil
}

// DownloadCount returns the value of the "download_count" field in the mutation.
func (m *BundleMutation) DownloadCount() (r int, exists bool) {
	v := m.download_count
	if v == nil {
		return
	}
	return *v, true
}

// OldDownloadCount returns the old "download_count" field's value of the Bundle entity.
// If the Bundle object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *BundleMutation) OldDownloadCount(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDownloadCount is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDownloadCount requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDownloadCount: %w", err)
	}
	return oldValue.DownloadCount, nil
}

// AddDownloadCount adds i to the "download_count" field.
func (m *BundleMutation) AddDownloadCount(i int) {
	if m.adddownload_count != nil {
		*m.adddownload_count += i
	} else {
		m.adddownload_count = &i
	}
}

// AddedDownloadCount returns the value that was added to the "download_count" field in this mutation.
func (m *BundleMutation) AddedDownloadCount() (r int, exists bool) {
	v := m.adddownload_count
	if v == nil {
		return
	}
	return *v, true
}

// ResetDownloadCount resets all changes to the "download_count" field.
func (m *BundleMutation) ResetDownloadCount() {
	m.download_count = nil
	m.adddownload_count = nil
}

// SetLegal sets the "legal" field.
func (m *BundleMutation) SetLegal(b bool) {
	m.legal = &b
}

// Legal returns the value of the "legal" field in the mutation.
func (m *BundleMutation) Legal() (r bool, exists bool) {
	v := m.legal
	if v == nil {
		return
	}
	return *v, true
}

// OldLegal returns the old "legal" field's value of the Bundle entity.
// If the Bundle object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *BundleMutation) OldLegal(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldLegal is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldLegal requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldLegal: %w", err)
	}
	return oldValue.Legal, nil
}

// ResetLegal resets all changes to the "legal" field.
func (m *BundleMutation) ResetLegal() {
	m.legal = nil
}

// SetMinGen sets the "min_gen" field.
func (m *BundleMutation) SetMinGen(s string) {
	m.min_gen = &s
}

// MinGen returns the value of the "min_gen" field in the mutation.
func (m *BundleMutation) MinGen() (r string, exists bool) {
	v := m.min_gen
	if v == nil {
		return
	}
	return *v, true
}

// OldMinGen returns the old "min_gen" field's value of the Bundle entity.
// If the Bundle object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *BundleMutation) OldMinGen(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldMinGen is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldMinGen requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldMinGen: %w", err)
	}
	return oldValue.MinGen, nil
}

// ResetMinGen resets all changes to the "min_gen" field.
func (m *BundleMutation) ResetMinGen() {
	m.min_gen = nil
}

// SetMaxGen sets the "max_gen" field.
func (m *BundleMutation) SetMaxGen(s string) {
	m.max_gen = &s
}

// MaxGen returns the value of the "max_gen" field in the mutation.
func (m *BundleMutation) MaxGen() (r string, exists bool) {
	v := m.max_gen
	if v == nil {
		return
	}
	return *v, true
}

// OldMaxGen returns the old "max_gen" field's value of the Bundle entity.
// If the Bundle object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *BundleMutation) OldMaxGen(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldMaxGen is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldMaxGen requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldMaxGen: %w", err)
	}
	return oldValue.MaxGen, nil
}

// ResetMaxGen resets all changes to the "max_gen" field.
func (m *BundleMutation) ResetMaxGen() {
	m.max_gen = nil
}

// AddPokemonIDs adds the "pokemons" edge to the Pokemon entity by ids.
func (m *BundleMutation) AddPokemonIDs(ids ...int) {
	if m.pokemons == nil {
		m.pokemons = make(map[int]struct{})
	}
	for i := range ids {
		m.pokemons[ids[i]] = struct{}{}
	}
}

// ClearPokemons clears the "pokemons" edge to the Pokemon entity.
func (m *BundleMutation) ClearPokemons() {
	m.clearedpokemons = true
}

// PokemonsCleared reports if the "pokemons" edge to the Pokemon entity was cleared.
func (m *BundleMutation) PokemonsCleared() bool {
	return m.clearedpokemons
}

// RemovePokemonIDs removes the "pokemons" edge to the Pokemon entity by IDs.
func (m *BundleMutation) RemovePokemonIDs(ids ...int) {
	if m.removedpokemons == nil {
		m.removedpokemons = make(map[int]struct{})
	}
	for i := range ids {
		delete(m.pokemons, ids[i])
		m.removedpokemons[ids[i]] = struct{}{}
	}
}

// RemovedPokemons returns the removed IDs of the "pokemons" edge to the Pokemon entity.
func (m *BundleMutation) RemovedPokemonsIDs() (ids []int) {
	for id := range m.removedpokemons {
		ids = append(ids, id)
	}
	return
}

// PokemonsIDs returns the "pokemons" edge IDs in the mutation.
func (m *BundleMutation) PokemonsIDs() (ids []int) {
	for id := range m.pokemons {
		ids = append(ids, id)
	}
	return
}

// ResetPokemons resets all changes to the "pokemons" edge.
func (m *BundleMutation) ResetPokemons() {
	m.pokemons = nil
	m.clearedpokemons = false
	m.removedpokemons = nil
}

// Where appends a list predicates to the BundleMutation builder.
func (m *BundleMutation) Where(ps ...predicate.Bundle) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the BundleMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *BundleMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Bundle, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *BundleMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *BundleMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Bundle).
func (m *BundleMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *BundleMutation) Fields() []string {
	fields := make([]string, 0, 6)
	if m.upload_datetime != nil {
		fields = append(fields, bundle.FieldUploadDatetime)
	}
	if m.download_code != nil {
		fields = append(fields, bundle.FieldDownloadCode)
	}
	if m.download_count != nil {
		fields = append(fields, bundle.FieldDownloadCount)
	}
	if m.legal != nil {
		fields = append(fields, bundle.FieldLegal)
	}
	if m.min_gen != nil {
		fields = append(fields, bundle.FieldMinGen)
	}
	if m.max_gen != nil {
		fields = append(fields, bundle.FieldMaxGen)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *BundleMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case bundle.FieldUploadDatetime:
		return m.UploadDatetime()
	case bundle.FieldDownloadCode:
		return m.DownloadCode()
	case bundle.FieldDownloadCount:
		return m.DownloadCount()
	case bundle.FieldLegal:
		return m.Legal()
	case bundle.FieldMinGen:
		return m.MinGen()
	case bundle.FieldMaxGen:
		return m.MaxGen()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *BundleMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case bundle.FieldUploadDatetime:
		return m.OldUploadDatetime(ctx)
	case bundle.FieldDownloadCode:
		return m.OldDownloadCode(ctx)
	case bundle.FieldDownloadCount:
		return m.OldDownloadCount(ctx)
	case bundle.FieldLegal:
		return m.OldLegal(ctx)
	case bundle.FieldMinGen:
		return m.OldMinGen(ctx)
	case bundle.FieldMaxGen:
		return m.OldMaxGen(ctx)
	}
	return nil, fmt.Errorf("unknown Bundle field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *BundleMutation) SetField(name string, value ent.Value) error {
	switch name {
	case bundle.FieldUploadDatetime:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUploadDatetime(v)
		return nil
	case bundle.FieldDownloadCode:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDownloadCode(v)
		return nil
	case bundle.FieldDownloadCount:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDownloadCount(v)
		return nil
	case bundle.FieldLegal:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetLegal(v)
		return nil
	case bundle.FieldMinGen:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetMinGen(v)
		return nil
	case bundle.FieldMaxGen:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetMaxGen(v)
		return nil
	}
	return fmt.Errorf("unknown Bundle field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *BundleMutation) AddedFields() []string {
	var fields []string
	if m.adddownload_count != nil {
		fields = append(fields, bundle.FieldDownloadCount)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *BundleMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case bundle.FieldDownloadCount:
		return m.AddedDownloadCount()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *BundleMutation) AddField(name string, value ent.Value) error {
	switch name {
	case bundle.FieldDownloadCount:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddDownloadCount(v)
		return nil
	}
	return fmt.Errorf("unknown Bundle numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *BundleMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *BundleMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *BundleMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Bundle nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *BundleMutation) ResetField(name string) error {
	switch name {
	case bundle.FieldUploadDatetime:
		m.ResetUploadDatetime()
		return nil
	case bundle.FieldDownloadCode:
		m.ResetDownloadCode()
		return nil
	case bundle.FieldDownloadCount:
		m.ResetDownloadCount()
		return nil
	case bundle.FieldLegal:
		m.ResetLegal()
		return nil
	case bundle.FieldMinGen:
		m.ResetMinGen()
		return nil
	case bundle.FieldMaxGen:
		m.ResetMaxGen()
		return nil
	}
	return fmt.Errorf("unknown Bundle field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *BundleMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.pokemons != nil {
		edges = append(edges, bundle.EdgePokemons)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *BundleMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case bundle.EdgePokemons:
		ids := make([]ent.Value, 0, len(m.pokemons))
		for id := range m.pokemons {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *BundleMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	if m.removedpokemons != nil {
		edges = append(edges, bundle.EdgePokemons)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *BundleMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case bundle.EdgePokemons:
		ids := make([]ent.Value, 0, len(m.removedpokemons))
		for id := range m.removedpokemons {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *BundleMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.clearedpokemons {
		edges = append(edges, bundle.EdgePokemons)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *BundleMutation) EdgeCleared(name string) bool {
	switch name {
	case bundle.EdgePokemons:
		return m.clearedpokemons
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *BundleMutation) ClearEdge(name string) error {
	switch name {
	}
	return fmt.Errorf("unknown Bundle unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *BundleMutation) ResetEdge(name string) error {
	switch name {
	case bundle.EdgePokemons:
		m.ResetPokemons()
		return nil
	}
	return fmt.Errorf("unknown Bundle edge %s", name)
}

// PokemonMutation represents an operation that mutates the Pokemon nodes in the graph.
type PokemonMutation struct {
	config
	op                Op
	typ               string
	id                *int
	upload_datetime   *time.Time
	download_code     *string
	download_count    *int
	adddownload_count *int
	generation        *string
	legal             *bool
	base_64           *string
	clearedFields     map[string]struct{}
	bundles           map[int]struct{}
	removedbundles    map[int]struct{}
	clearedbundles    bool
	done              bool
	oldValue          func(context.Context) (*Pokemon, error)
	predicates        []predicate.Pokemon
}

var _ ent.Mutation = (*PokemonMutation)(nil)

// pokemonOption allows management of the mutation configuration using functional options.
type pokemonOption func(*PokemonMutation)

// newPokemonMutation creates new mutation for the Pokemon entity.
func newPokemonMutation(c config, op Op, opts ...pokemonOption) *PokemonMutation {
	m := &PokemonMutation{
		config:        c,
		op:            op,
		typ:           TypePokemon,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withPokemonID sets the ID field of the mutation.
func withPokemonID(id int) pokemonOption {
	return func(m *PokemonMutation) {
		var (
			err   error
			once  sync.Once
			value *Pokemon
		)
		m.oldValue = func(ctx context.Context) (*Pokemon, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Pokemon.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withPokemon sets the old Pokemon of the mutation.
func withPokemon(node *Pokemon) pokemonOption {
	return func(m *PokemonMutation) {
		m.oldValue = func(context.Context) (*Pokemon, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m PokemonMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m PokemonMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *PokemonMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *PokemonMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Pokemon.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetUploadDatetime sets the "upload_datetime" field.
func (m *PokemonMutation) SetUploadDatetime(t time.Time) {
	m.upload_datetime = &t
}

// UploadDatetime returns the value of the "upload_datetime" field in the mutation.
func (m *PokemonMutation) UploadDatetime() (r time.Time, exists bool) {
	v := m.upload_datetime
	if v == nil {
		return
	}
	return *v, true
}

// OldUploadDatetime returns the old "upload_datetime" field's value of the Pokemon entity.
// If the Pokemon object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PokemonMutation) OldUploadDatetime(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUploadDatetime is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUploadDatetime requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUploadDatetime: %w", err)
	}
	return oldValue.UploadDatetime, nil
}

// ResetUploadDatetime resets all changes to the "upload_datetime" field.
func (m *PokemonMutation) ResetUploadDatetime() {
	m.upload_datetime = nil
}

// SetDownloadCode sets the "download_code" field.
func (m *PokemonMutation) SetDownloadCode(s string) {
	m.download_code = &s
}

// DownloadCode returns the value of the "download_code" field in the mutation.
func (m *PokemonMutation) DownloadCode() (r string, exists bool) {
	v := m.download_code
	if v == nil {
		return
	}
	return *v, true
}

// OldDownloadCode returns the old "download_code" field's value of the Pokemon entity.
// If the Pokemon object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PokemonMutation) OldDownloadCode(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDownloadCode is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDownloadCode requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDownloadCode: %w", err)
	}
	return oldValue.DownloadCode, nil
}

// ResetDownloadCode resets all changes to the "download_code" field.
func (m *PokemonMutation) ResetDownloadCode() {
	m.download_code = nil
}

// SetDownloadCount sets the "download_count" field.
func (m *PokemonMutation) SetDownloadCount(i int) {
	m.download_count = &i
	m.adddownload_count = nil
}

// DownloadCount returns the value of the "download_count" field in the mutation.
func (m *PokemonMutation) DownloadCount() (r int, exists bool) {
	v := m.download_count
	if v == nil {
		return
	}
	return *v, true
}

// OldDownloadCount returns the old "download_count" field's value of the Pokemon entity.
// If the Pokemon object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PokemonMutation) OldDownloadCount(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDownloadCount is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDownloadCount requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDownloadCount: %w", err)
	}
	return oldValue.DownloadCount, nil
}

// AddDownloadCount adds i to the "download_count" field.
func (m *PokemonMutation) AddDownloadCount(i int) {
	if m.adddownload_count != nil {
		*m.adddownload_count += i
	} else {
		m.adddownload_count = &i
	}
}

// AddedDownloadCount returns the value that was added to the "download_count" field in this mutation.
func (m *PokemonMutation) AddedDownloadCount() (r int, exists bool) {
	v := m.adddownload_count
	if v == nil {
		return
	}
	return *v, true
}

// ResetDownloadCount resets all changes to the "download_count" field.
func (m *PokemonMutation) ResetDownloadCount() {
	m.download_count = nil
	m.adddownload_count = nil
}

// SetGeneration sets the "generation" field.
func (m *PokemonMutation) SetGeneration(s string) {
	m.generation = &s
}

// Generation returns the value of the "generation" field in the mutation.
func (m *PokemonMutation) Generation() (r string, exists bool) {
	v := m.generation
	if v == nil {
		return
	}
	return *v, true
}

// OldGeneration returns the old "generation" field's value of the Pokemon entity.
// If the Pokemon object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PokemonMutation) OldGeneration(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldGeneration is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldGeneration requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldGeneration: %w", err)
	}
	return oldValue.Generation, nil
}

// ResetGeneration resets all changes to the "generation" field.
func (m *PokemonMutation) ResetGeneration() {
	m.generation = nil
}

// SetLegal sets the "legal" field.
func (m *PokemonMutation) SetLegal(b bool) {
	m.legal = &b
}

// Legal returns the value of the "legal" field in the mutation.
func (m *PokemonMutation) Legal() (r bool, exists bool) {
	v := m.legal
	if v == nil {
		return
	}
	return *v, true
}

// OldLegal returns the old "legal" field's value of the Pokemon entity.
// If the Pokemon object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PokemonMutation) OldLegal(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldLegal is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldLegal requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldLegal: %w", err)
	}
	return oldValue.Legal, nil
}

// ResetLegal resets all changes to the "legal" field.
func (m *PokemonMutation) ResetLegal() {
	m.legal = nil
}

// SetBase64 sets the "base_64" field.
func (m *PokemonMutation) SetBase64(s string) {
	m.base_64 = &s
}

// Base64 returns the value of the "base_64" field in the mutation.
func (m *PokemonMutation) Base64() (r string, exists bool) {
	v := m.base_64
	if v == nil {
		return
	}
	return *v, true
}

// OldBase64 returns the old "base_64" field's value of the Pokemon entity.
// If the Pokemon object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PokemonMutation) OldBase64(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldBase64 is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldBase64 requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldBase64: %w", err)
	}
	return oldValue.Base64, nil
}

// ResetBase64 resets all changes to the "base_64" field.
func (m *PokemonMutation) ResetBase64() {
	m.base_64 = nil
}

// AddBundleIDs adds the "bundles" edge to the Bundle entity by ids.
func (m *PokemonMutation) AddBundleIDs(ids ...int) {
	if m.bundles == nil {
		m.bundles = make(map[int]struct{})
	}
	for i := range ids {
		m.bundles[ids[i]] = struct{}{}
	}
}

// ClearBundles clears the "bundles" edge to the Bundle entity.
func (m *PokemonMutation) ClearBundles() {
	m.clearedbundles = true
}

// BundlesCleared reports if the "bundles" edge to the Bundle entity was cleared.
func (m *PokemonMutation) BundlesCleared() bool {
	return m.clearedbundles
}

// RemoveBundleIDs removes the "bundles" edge to the Bundle entity by IDs.
func (m *PokemonMutation) RemoveBundleIDs(ids ...int) {
	if m.removedbundles == nil {
		m.removedbundles = make(map[int]struct{})
	}
	for i := range ids {
		delete(m.bundles, ids[i])
		m.removedbundles[ids[i]] = struct{}{}
	}
}

// RemovedBundles returns the removed IDs of the "bundles" edge to the Bundle entity.
func (m *PokemonMutation) RemovedBundlesIDs() (ids []int) {
	for id := range m.removedbundles {
		ids = append(ids, id)
	}
	return
}

// BundlesIDs returns the "bundles" edge IDs in the mutation.
func (m *PokemonMutation) BundlesIDs() (ids []int) {
	for id := range m.bundles {
		ids = append(ids, id)
	}
	return
}

// ResetBundles resets all changes to the "bundles" edge.
func (m *PokemonMutation) ResetBundles() {
	m.bundles = nil
	m.clearedbundles = false
	m.removedbundles = nil
}

// Where appends a list predicates to the PokemonMutation builder.
func (m *PokemonMutation) Where(ps ...predicate.Pokemon) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the PokemonMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *PokemonMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Pokemon, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *PokemonMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *PokemonMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Pokemon).
func (m *PokemonMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *PokemonMutation) Fields() []string {
	fields := make([]string, 0, 6)
	if m.upload_datetime != nil {
		fields = append(fields, pokemon.FieldUploadDatetime)
	}
	if m.download_code != nil {
		fields = append(fields, pokemon.FieldDownloadCode)
	}
	if m.download_count != nil {
		fields = append(fields, pokemon.FieldDownloadCount)
	}
	if m.generation != nil {
		fields = append(fields, pokemon.FieldGeneration)
	}
	if m.legal != nil {
		fields = append(fields, pokemon.FieldLegal)
	}
	if m.base_64 != nil {
		fields = append(fields, pokemon.FieldBase64)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *PokemonMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case pokemon.FieldUploadDatetime:
		return m.UploadDatetime()
	case pokemon.FieldDownloadCode:
		return m.DownloadCode()
	case pokemon.FieldDownloadCount:
		return m.DownloadCount()
	case pokemon.FieldGeneration:
		return m.Generation()
	case pokemon.FieldLegal:
		return m.Legal()
	case pokemon.FieldBase64:
		return m.Base64()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *PokemonMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case pokemon.FieldUploadDatetime:
		return m.OldUploadDatetime(ctx)
	case pokemon.FieldDownloadCode:
		return m.OldDownloadCode(ctx)
	case pokemon.FieldDownloadCount:
		return m.OldDownloadCount(ctx)
	case pokemon.FieldGeneration:
		return m.OldGeneration(ctx)
	case pokemon.FieldLegal:
		return m.OldLegal(ctx)
	case pokemon.FieldBase64:
		return m.OldBase64(ctx)
	}
	return nil, fmt.Errorf("unknown Pokemon field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *PokemonMutation) SetField(name string, value ent.Value) error {
	switch name {
	case pokemon.FieldUploadDatetime:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUploadDatetime(v)
		return nil
	case pokemon.FieldDownloadCode:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDownloadCode(v)
		return nil
	case pokemon.FieldDownloadCount:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDownloadCount(v)
		return nil
	case pokemon.FieldGeneration:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetGeneration(v)
		return nil
	case pokemon.FieldLegal:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetLegal(v)
		return nil
	case pokemon.FieldBase64:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetBase64(v)
		return nil
	}
	return fmt.Errorf("unknown Pokemon field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *PokemonMutation) AddedFields() []string {
	var fields []string
	if m.adddownload_count != nil {
		fields = append(fields, pokemon.FieldDownloadCount)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *PokemonMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case pokemon.FieldDownloadCount:
		return m.AddedDownloadCount()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *PokemonMutation) AddField(name string, value ent.Value) error {
	switch name {
	case pokemon.FieldDownloadCount:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddDownloadCount(v)
		return nil
	}
	return fmt.Errorf("unknown Pokemon numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *PokemonMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *PokemonMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *PokemonMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Pokemon nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *PokemonMutation) ResetField(name string) error {
	switch name {
	case pokemon.FieldUploadDatetime:
		m.ResetUploadDatetime()
		return nil
	case pokemon.FieldDownloadCode:
		m.ResetDownloadCode()
		return nil
	case pokemon.FieldDownloadCount:
		m.ResetDownloadCount()
		return nil
	case pokemon.FieldGeneration:
		m.ResetGeneration()
		return nil
	case pokemon.FieldLegal:
		m.ResetLegal()
		return nil
	case pokemon.FieldBase64:
		m.ResetBase64()
		return nil
	}
	return fmt.Errorf("unknown Pokemon field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *PokemonMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.bundles != nil {
		edges = append(edges, pokemon.EdgeBundles)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *PokemonMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case pokemon.EdgeBundles:
		ids := make([]ent.Value, 0, len(m.bundles))
		for id := range m.bundles {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *PokemonMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	if m.removedbundles != nil {
		edges = append(edges, pokemon.EdgeBundles)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *PokemonMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case pokemon.EdgeBundles:
		ids := make([]ent.Value, 0, len(m.removedbundles))
		for id := range m.removedbundles {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *PokemonMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.clearedbundles {
		edges = append(edges, pokemon.EdgeBundles)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *PokemonMutation) EdgeCleared(name string) bool {
	switch name {
	case pokemon.EdgeBundles:
		return m.clearedbundles
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *PokemonMutation) ClearEdge(name string) error {
	switch name {
	}
	return fmt.Errorf("unknown Pokemon unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *PokemonMutation) ResetEdge(name string) error {
	switch name {
	case pokemon.EdgeBundles:
		m.ResetBundles()
		return nil
	}
	return fmt.Errorf("unknown Pokemon edge %s", name)
}
