// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/FlagBrew/local-gpss/internal/database/ent/bundle"
	"github.com/FlagBrew/local-gpss/internal/database/ent/pokemon"
	"github.com/FlagBrew/local-gpss/internal/database/ent/predicate"
)

// PokemonUpdate is the builder for updating Pokemon entities.
type PokemonUpdate struct {
	config
	hooks    []Hook
	mutation *PokemonMutation
}

// Where appends a list predicates to the PokemonUpdate builder.
func (_u *PokemonUpdate) Where(ps ...predicate.Pokemon) *PokemonUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUploadDatetime sets the "upload_datetime" field.
func (_u *PokemonUpdate) SetUploadDatetime(v time.Time) *PokemonUpdate {
	_u.mutation.SetUploadDatetime(v)
	return _u
}

// SetNillableUploadDatetime sets the "upload_datetime" field if the given value is not nil.
func (_u *PokemonUpdate) SetNillableUploadDatetime(v *time.Time) *PokemonUpdate {
	if v != nil {
		_u.SetUploadDatetime(*v)
	}
	return _u
}

// SetDownloadCode sets the "download_code" field.
func (_u *PokemonUpdate) SetDownloadCode(v string) *PokemonUpdate {
	_u.mutation.SetDownloadCode(v)
	return _u
}

// SetNillableDownloadCode sets the "download_code" field if the given value is not nil.
func (_u *PokemonUpdate) SetNillableDownloadCode(v *string) *PokemonUpdate {
	if v != nil {
		_u.SetDownloadCode(*v)
	}
	return _u
}

// SetDownloadCount sets the "download_count" field.
func (_u *PokemonUpdate) SetDownloadCount(v int) *PokemonUpdate {
	_u.mutation.ResetDownloadCount()
	_u.mutation.SetDownloadCount(v)
	return _u
}

// SetNillableDownloadCount sets the "download_count" field if the given value is not nil.
func (_u *PokemonUpdate) SetNillableDownloadCount(v *int) *PokemonUpdate {
	if v != nil {
		_u.SetDownloadCount(*v)
	}
	return _u
}

// AddDownloadCount adds value to the "download_count" field.
func (_u *PokemonUpdate) AddDownloadCount(v int) *PokemonUpdate {
	_u.mutation.AddDownloadCount(v)
	return _u
}

// SetGeneration sets the "generation" field.
func (_u *PokemonUpdate) SetGeneration(v string) *PokemonUpdate {
	_u.mutation.SetGeneration(v)
	return _u
}

// SetNillableGeneration sets the "generation" field if the given value is not nil.
func (_u *PokemonUpdate) SetNillableGeneration(v *string) *PokemonUpdate {
	if v != nil {
		_u.SetGeneration(*v)
	}
	return _u
}

// SetLegal sets the "legal" field.
func (_u *PokemonUpdate) SetLegal(v bool) *PokemonUpdate {
	_u.mutation.SetLegal(v)
	return _u
}

// SetNillableLegal sets the "legal" field if the given value is not nil.
func (_u *PokemonUpdate) SetNillableLegal(v *bool) *PokemonUpdate {
	if v != nil {
		_u.SetLegal(*v)
	}
	return _u
}

// SetBase64 sets the "base_64" field.
func (_u *PokemonUpdate) SetBase64(v string) *PokemonUpdate {
	_u.mutation.SetBase64(v)
	return _u
}

// SetNillableBase64 sets the "base_64" field if the given value is not nil.
func (_u *PokemonUpdate) SetNillableBase64(v *string) *PokemonUpdate {
	if v != nil {
		_u.SetBase64(*v)
	}
	return _u
}

// AddBundleIDs adds the "bundles" edge to the Bundle entity by IDs.
func (_u *PokemonUpdate) AddBundleIDs(ids ...int) *PokemonUpdate {
	_u.mutation.AddBundleIDs(ids...)
	return _u
}

// AddBundles adds the "bundles" edges to the Bundle entity.
func (_u *PokemonUpdate) AddBundles(v ...*Bundle) *PokemonUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBundleIDs(ids...)
}

// Mutation returns the PokemonMutation object of the builder.
func (_u *PokemonUpdate) Mutation() *PokemonMutation {
	return _u.mutation
}

// ClearBundles clears all "bundles" edges to the Bundle entity.
func (_u *PokemonUpdate) ClearBundles() *PokemonUpdate {
	_u.mutation.ClearBundles()
	return _u
}

// RemoveBundleIDs removes the "bundles" edge to Bundle entities by IDs.
func (_u *PokemonUpdate) RemoveBundleIDs(ids ...int) *PokemonUpdate {
	_u.mutation.RemoveBundleIDs(ids...)
	return _u
}

// RemoveBundles removes "bundles" edges to Bundle entities.
func (_u *PokemonUpdate) RemoveBundles(v ...*Bundle) *PokemonUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBundleIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PokemonUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PokemonUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PokemonUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PokemonUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *PokemonUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(pokemon.Table, pokemon.Columns, sqlgraph.NewFieldSpec(pokemon.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UploadDatetime(); ok {
		_spec.SetField(pokemon.FieldUploadDatetime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DownloadCode(); ok {
		_spec.SetField(pokemon.FieldDownloadCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.DownloadCount(); ok {
		_spec.SetField(pokemon.FieldDownloadCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDownloadCount(); ok {
		_spec.AddField(pokemon.FieldDownloadCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Generation(); ok {
		_spec.SetField(pokemon.FieldGeneration, field.TypeString, value)
	}
	if value, ok := _u.mutation.Legal(); ok {
		_spec.SetField(pokemon.FieldLegal, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Base64(); ok {
		_spec.SetField(pokemon.FieldBase64, field.TypeString, value)
	}
	if _u.mutation.BundlesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   pokemon.BundlesTable,
			Columns: pokemon.BundlesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bundle.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBundlesIDs(); len(nodes) > 0 && !_u.mutation.BundlesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   pokemon.BundlesTable,
			Columns: pokemon.BundlesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bundle.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BundlesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   pokemon.BundlesTable,
			Columns: pokemon.BundlesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bundle.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pokemon.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PokemonUpdateOne is the builder for updating a single Pokemon entity.
type PokemonUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PokemonMutation
}

// SetUploadDatetime sets the "upload_datetime" field.
func (_u *PokemonUpdateOne) SetUploadDatetime(v time.Time) *PokemonUpdateOne {
	_u.mutation.SetUploadDatetime(v)
	return _u
}

// SetNillableUploadDatetime sets the "upload_datetime" field if the given value is not nil.
func (_u *PokemonUpdateOne) SetNillableUploadDatetime(v *time.Time) *PokemonUpdateOne {
	if v != nil {
		_u.SetUploadDatetime(*v)
	}
	return _u
}

// SetDownloadCode sets the "download_code" field.
func (_u *PokemonUpdateOne) SetDownloadCode(v string) *PokemonUpdateOne {
	_u.mutation.SetDownloadCode(v)
	return _u
}

// SetNillableDownloadCode sets the "download_code" field if the given value is not nil.
func (_u *PokemonUpdateOne) SetNillableDownloadCode(v *string) *PokemonUpdateOne {
	if v != nil {
		_u.SetDownloadCode(*v)
	}
	return _u
}

// SetDownloadCount sets the "download_count" field.
func (_u *PokemonUpdateOne) SetDownloadCount(v int) *PokemonUpdateOne {
	_u.mutation.ResetDownloadCount()
	_u.mutation.SetDownloadCount(v)
	return _u
}

// SetNillableDownloadCount sets the "download_count" field if the given value is not nil.
func (_u *PokemonUpdateOne) SetNillableDownloadCount(v *int) *PokemonUpdateOne {
	if v != nil {
		_u.SetDownloadCount(*v)
	}
	return _u
}

// AddDownloadCount adds value to the "download_count" field.
func (_u *PokemonUpdateOne) AddDownloadCount(v int) *PokemonUpdateOne {
	_u.mutation.AddDownloadCount(v)
	return _u
}

// SetGeneration sets the "generation" field.
func (_u *PokemonUpdateOne) SetGeneration(v string) *PokemonUpdateOne {
	_u.mutation.SetGeneration(v)
	return _u
}

// SetNillableGeneration sets the "generation" field if the given value is not nil.
func (_u *PokemonUpdateOne) SetNillableGeneration(v *string) *PokemonUpdateOne {
	if v != nil {
		_u.SetGeneration(*v)
	}
	return _u
}

// SetLegal sets the "legal" field.
func (_u *PokemonUpdateOne) SetLegal(v bool) *PokemonUpdateOne {
	_u.mutation.SetLegal(v)
	return _u
}

// SetNillableLegal sets the "legal" field if the given value is not nil.
func (_u *PokemonUpdateOne) SetNillableLegal(v *bool) *PokemonUpdateOne {
	if v != nil {
		_u.SetLegal(*v)
	}
	return _u
}

// SetBase64 sets the "base_64" field.
func (_u *PokemonUpdateOne) SetBase64(v string) *PokemonUpdateOne {
	_u.mutation.SetBase64(v)
	return _u
}

// SetNillableBase64 sets the "base_64" field if the given value is not nil.
func (_u *PokemonUpdateOne) SetNillableBase64(v *string) *PokemonUpdateOne {
	if v != nil {
		_u.SetBase64(*v)
	}
	return _u
}

// AddBundleIDs adds the "bundles" edge to the Bundle entity by IDs.
func (_u *PokemonUpdateOne) AddBundleIDs(ids ...int) *PokemonUpdateOne {
	_u.mutation.AddBundleIDs(ids...)
	return _u
}

// AddBundles adds the "bundles" edges to the Bundle entity.
func (_u *PokemonUpdateOne) AddBundles(v ...*Bundle) *PokemonUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBundleIDs(ids...)
}

// Mutation returns the PokemonMutation object of the builder.
func (_u *PokemonUpdateOne) Mutation() *PokemonMutation {
	return _u.mutation
}

// ClearBundles clears all "bundles" edges to the Bundle entity.
func (_u *PokemonUpdateOne) ClearBundles() *PokemonUpdateOne {
	_u.mutation.ClearBundles()
	return _u
}

// RemoveBundleIDs removes the "bundles" edge to Bundle entities by IDs.
func (_u *PokemonUpdateOne) RemoveBundleIDs(ids ...int) *PokemonUpdateOne {
	_u.mutation.RemoveBundleIDs(ids...)
	return _u
}

// RemoveBundles removes "bundles" edges to Bundle entities.
func (_u *PokemonUpdateOne) RemoveBundles(v ...*Bundle) *PokemonUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBundleIDs(ids...)
}

// Where appends a list predicates to the PokemonUpdate builder.
func (_u *PokemonUpdateOne) Where(ps ...predicate.Pokemon) *PokemonUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PokemonUpdateOne) Select(field string, fields ...string) *PokemonUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Pokemon entity.
func (_u *PokemonUpdateOne) Save(ctx context.Context) (*Pokemon, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PokemonUpdateOne) SaveX(ctx context.Context) *Pokemon {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PokemonUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PokemonUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *PokemonUpdateOne) sqlSave(ctx context.Context) (_node *Pokemon, err error) {
	_spec := sqlgraph.NewUpdateSpec(pokemon.Table, pokemon.Columns, sqlgraph.NewFieldSpec(pokemon.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Pokemon.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, pokemon.FieldID)
		for _, f := range fields {
			if !pokemon.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != pokemon.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UploadDatetime(); ok {
		_spec.SetField(pokemon.FieldUploadDatetime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DownloadCode(); ok {
		_spec.SetField(pokemon.FieldDownloadCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.DownloadCount(); ok {
		_spec.SetField(pokemon.FieldDownloadCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDownloadCount(); ok {
		_spec.AddField(pokemon.FieldDownloadCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Generation(); ok {
		_spec.SetField(pokemon.FieldGeneration, field.TypeString, value)
	}
	if value, ok := _u.mutation.Legal(); ok {
		_spec.SetField(pokemon.FieldLegal, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Base64(); ok {
		_spec.SetField(pokemon.FieldBase64, field.TypeString, value)
	}
	if _u.mutation.BundlesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   pokemon.BundlesTable,
			Columns: pokemon.BundlesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bundle.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBundlesIDs(); len(nodes) > 0 && !_u.mutation.BundlesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   pokemon.BundlesTable,
			Columns: pokemon.BundlesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bundle.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BundlesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   pokemon.BundlesTable,
			Columns: pokemon.BundlesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bundle.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Pokemon{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pokemon.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
