// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/FlagBrew/local-gpss/internal/database/ent/pokemon"
	"github.com/FlagBrew/local-gpss/internal/database/ent/predicate"
)

// PokemonDelete is the builder for deleting a Pokemon entity.
type PokemonDelete struct {
	config
	hooks    []Hook
	mutation *PokemonMutation
}

// Where appends a list predicates to the PokemonDelete builder.
func (_d *PokemonDelete) Where(ps ...predicate.Pokemon) *PokemonDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *PokemonDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PokemonDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *PokemonDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(pokemon.Table, sqlgraph.NewFieldSpec(pokemon.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// PokemonDeleteOne is the builder for deleting a single Pokemon entity.
type PokemonDeleteOne struct {
	_d *PokemonDelete
}

// Where appends a list predicates to the PokemonDelete builder.
func (_d *PokemonDeleteOne) Where(ps ...predicate.Pokemon) *PokemonDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *PokemonDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{pokemon.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PokemonDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
