// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/FlagBrew/local-gpss/internal/database/ent/bundle"
	"github.com/FlagBrew/local-gpss/internal/database/ent/pokemon"
)

// PokemonCreate is the builder for creating a Pokemon entity.
type PokemonCreate struct {
	config
	mutation *PokemonMutation
	hooks    []Hook
}

// SetUploadDatetime sets the "upload_datetime" field.
func (_c *PokemonCreate) SetUploadDatetime(v time.Time) *PokemonCreate {
	_c.mutation.SetUploadDatetime(v)
	return _c
}

// SetDownloadCode sets the "download_code" field.
func (_c *PokemonCreate) SetDownloadCode(v string) *PokemonCreate {
	_c.mutation.SetDownloadCode(v)
	return _c
}

// SetDownloadCount sets the "download_count" field.
func (_c *PokemonCreate) SetDownloadCount(v int) *PokemonCreate {
	_c.mutation.SetDownloadCount(v)
	return _c
}

// SetGeneration sets the "generation" field.
func (_c *PokemonCreate) SetGeneration(v string) *PokemonCreate {
	_c.mutation.SetGeneration(v)
	return _c
}

// SetLegal sets the "legal" field.
func (_c *PokemonCreate) SetLegal(v bool) *PokemonCreate {
	_c.mutation.SetLegal(v)
	return _c
}

// SetBase64 sets the "base_64" field.
func (_c *PokemonCreate) SetBase64(v string) *PokemonCreate {
	_c.mutation.SetBase64(v)
	return _c
}

// SetID sets the "id" field.
func (_c *PokemonCreate) SetID(v int) *PokemonCreate {
	_c.mutation.SetID(v)
	return _c
}

// AddBundleIDs adds the "bundles" edge to the Bundle entity by IDs.
func (_c *PokemonCreate) AddBundleIDs(ids ...int) *PokemonCreate {
	_c.mutation.AddBundleIDs(ids...)
	return _c
}

// AddBundles adds the "bundles" edges to the Bundle entity.
func (_c *PokemonCreate) AddBundles(v ...*Bundle) *PokemonCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddBundleIDs(ids...)
}

// Mutation returns the PokemonMutation object of the builder.
func (_c *PokemonCreate) Mutation() *PokemonMutation {
	return _c.mutation
}

// Save creates the Pokemon in the database.
func (_c *PokemonCreate) Save(ctx context.Context) (*Pokemon, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PokemonCreate) SaveX(ctx context.Context) *Pokemon {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PokemonCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PokemonCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PokemonCreate) check() error {
	if _, ok := _c.mutation.UploadDatetime(); !ok {
		return &ValidationError{Name: "upload_datetime", err: errors.New(`ent: missing required field "Pokemon.upload_datetime"`)}
	}
	if _, ok := _c.mutation.DownloadCode(); !ok {
		return &ValidationError{Name: "download_code", err: errors.New(`ent: missing required field "Pokemon.download_code"`)}
	}
	if _, ok := _c.mutation.DownloadCount(); !ok {
		return &ValidationError{Name: "download_count", err: errors.New(`ent: missing required field "Pokemon.download_count"`)}
	}
	if _, ok := _c.mutation.Generation(); !ok {
		return &ValidationError{Name: "generation", err: errors.New(`ent: missing required field "Pokemon.generation"`)}
	}
	if _, ok := _c.mutation.Legal(); !ok {
		return &ValidationError{Name: "legal", err: errors.New(`ent: missing required field "Pokemon.legal"`)}
	}
	if _, ok := _c.mutation.Base64(); !ok {
		return &ValidationError{Name: "base_64", err: errors.New(`ent: missing required field "Pokemon.base_64"`)}
	}
	return nil
}

func (_c *PokemonCreate) sqlSave(ctx context.Context) (*Pokemon, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PokemonCreate) createSpec() (*Pokemon, *sqlgraph.CreateSpec) {
	var (
		_node = &Pokemon{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(pokemon.Table, sqlgraph.NewFieldSpec(pokemon.FieldID, field.TypeInt))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.UploadDatetime(); ok {
		_spec.SetField(pokemon.FieldUploadDatetime, field.TypeTime, value)
		_node.UploadDatetime = value
	}
	if value, ok := _c.mutation.DownloadCode(); ok {
		_spec.SetField(pokemon.FieldDownloadCode, field.TypeString, value)
		_node.DownloadCode = value
	}
	if value, ok := _c.mutation.DownloadCount(); ok {
		_spec.SetField(pokemon.FieldDownloadCount, field.TypeInt, value)
		_node.DownloadCount = value
	}
	if value, ok := _c.mutation.Generation(); ok {
		_spec.SetField(pokemon.FieldGeneration, field.TypeString, value)
		_node.Generation = value
	}
	if value, ok := _c.mutation.Legal(); ok {
		_spec.SetField(pokemon.FieldLegal, field.TypeBool, value)
		_node.Legal = value
	}
	if value, ok := _c.mutation.Base64(); ok {
		_spec.SetField(pokemon.FieldBase64, field.TypeString, value)
		_node.Base64 = value
	}
	if nodes := _c.mutation.BundlesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   pokemon.BundlesTable,
			Columns: pokemon.BundlesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bundle.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PokemonCreateBulk is the builder for creating many Pokemon entities in bulk.
type PokemonCreateBulk struct {
	config
	err      error
	builders []*PokemonCreate
}

// Save creates the Pokemon entities in the database.
func (_c *PokemonCreateBulk) Save(ctx context.Context) ([]*Pokemon, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Pokemon, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PokemonMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PokemonCreateBulk) SaveX(ctx context.Context) []*Pokemon {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PokemonCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PokemonCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
