// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/FlagBrew/local-gpss/internal/database/ent/pokemon"
)

// Pokemon is the model entity for the Pokemon schema.
type Pokemon struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// UploadDatetime holds the value of the "upload_datetime" field.
	UploadDatetime time.Time `json:"upload_datetime,omitempty"`
	// DownloadCode holds the value of the "download_code" field.
	DownloadCode string `json:"download_code,omitempty"`
	// DownloadCount holds the value of the "download_count" field.
	DownloadCount int `json:"download_count,omitempty"`
	// Generation holds the value of the "generation" field.
	Generation string `json:"generation,omitempty"`
	// Legal holds the value of the "legal" field.
	Legal bool `json:"legal,omitempty"`
	// Base64 holds the value of the "base_64" field.
	Base64 string `json:"base_64,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PokemonQuery when eager-loading is set.
	Edges        PokemonEdges `json:"edges"`
	selectValues sql.SelectValues
}

// PokemonEdges holds the relations/edges for other nodes in the graph.
type PokemonEdges struct {
	// Bundles holds the value of the bundles edge.
	Bundles []*Bundle `json:"bundles,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// BundlesOrErr returns the Bundles value or an error if the edge
// was not loaded in eager-loading.
func (e PokemonEdges) BundlesOrErr() ([]*Bundle, error) {
	if e.loadedTypes[0] {
		return e.Bundles, nil
	}
	return nil, &NotLoadedError{edge: "bundles"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Pokemon) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case pokemon.FieldLegal:
			values[i] = new(sql.NullBool)
		case pokemon.FieldID, pokemon.FieldDownloadCount:
			values[i] = new(sql.NullInt64)
		case pokemon.FieldDownloadCode, pokemon.FieldGeneration, pokemon.FieldBase64:
			values[i] = new(sql.NullString)
		case pokemon.FieldUploadDatetime:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Pokemon fields.
func (_m *Pokemon) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case pokemon.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case pokemon.FieldUploadDatetime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field upload_datetime", values[i])
			} else if value.Valid {
				_m.UploadDatetime = value.Time
			}
		case pokemon.FieldDownloadCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field download_code", values[i])
			} else if value.Valid {
				_m.DownloadCode = value.String
			}
		case pokemon.FieldDownloadCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field download_count", values[i])
			} else if value.Valid {
				_m.DownloadCount = int(value.Int64)
			}
		case pokemon.FieldGeneration:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field generation", values[i])
			} else if value.Valid {
				_m.Generation = value.String
			}
		case pokemon.FieldLegal:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field legal", values[i])
			} else if value.Valid {
				_m.Legal = value.Bool
			}
		case pokemon.FieldBase64:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field base_64", values[i])
			} else if value.Valid {
				_m.Base64 = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Pokemon.
// This includes values selected through modifiers, order, etc.
func (_m *Pokemon) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryBundles queries the "bundles" edge of the Pokemon entity.
func (_m *Pokemon) QueryBundles() *BundleQuery {
	return NewPokemonClient(_m.config).QueryBundles(_m)
}

// Update returns a builder for updating this Pokemon.
// Note that you need to call Pokemon.Unwrap() before calling this method if this Pokemon
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Pokemon) Update() *PokemonUpdateOne {
	return NewPokemonClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Pokemon entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Pokemon) Unwrap() *Pokemon {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Pokemon is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Pokemon) String() string {
	var builder strings.Builder
	builder.WriteString("Pokemon(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("upload_datetime=")
	builder.WriteString(_m.UploadDatetime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("download_code=")
	builder.WriteString(_m.DownloadCode)
	builder.WriteString(", ")
	builder.WriteString("download_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.DownloadCount))
	builder.WriteString(", ")
	builder.WriteString("generation=")
	builder.WriteString(_m.Generation)
	builder.WriteString(", ")
	builder.WriteString("legal=")
	builder.WriteString(fmt.Sprintf("%v", _m.Legal))
	builder.WriteString(", ")
	builder.WriteString("base_64=")
	builder.WriteString(_m.Base64)
	builder.WriteByte(')')
	return builder.String()
}

// Pokemons is a parsable slice of Pokemon.
type Pokemons []*Pokemon
