// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// BundlesColumns holds the columns for the "bundles" table.
	BundlesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "upload_datetime", Type: field.TypeTime},
		{Name: "download_code", Type: field.TypeString, Unique: true},
		{Name: "download_count", Type: field.TypeInt, Default: 0},
		{Name: "legal", Type: field.TypeBool},
		{Name: "min_gen", Type: field.TypeString},
		{Name: "max_gen", Type: field.TypeString},
	}
	// BundlesTable holds the schema information for the "bundles" table.
	BundlesTable = &schema.Table{
		Name:       "bundles",
		Columns:    BundlesColumns,
		PrimaryKey: []*schema.Column{BundlesColumns[0]},
	}
	// PokemonsColumns holds the columns for the "pokemons" table.
	PokemonsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "upload_datetime", Type: field.TypeTime},
		{Name: "download_code", Type: field.TypeString, Unique: true},
		{Name: "download_count", Type: field.TypeInt, Default: 0},
		{Name: "generation", Type: field.TypeString},
		{Name: "legal", Type: field.TypeBool},
		{Name: "base_64", Type: field.TypeString},
	}
	// PokemonsTable holds the schema information for the "pokemons" table.
	PokemonsTable = &schema.Table{
		Name:       "pokemons",
		Columns:    PokemonsColumns,
		PrimaryKey: []*schema.Column{PokemonsColumns[0]},
	}
	// BundlePokemonsColumns holds the columns for the "bundle_pokemons" table.
	BundlePokemonsColumns = []*schema.Column{
		{Name: "bundle_id", Type: field.TypeInt},
		{Name: "pokemon_id", Type: field.TypeInt},
	}
	// BundlePokemonsTable holds the schema information for the "bundle_pokemons" table.
	BundlePokemonsTable = &schema.Table{
		Name:       "bundle_pokemons",
		Columns:    BundlePokemonsColumns,
		PrimaryKey: []*schema.Column{BundlePokemonsColumns[0], BundlePokemonsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "bundle_pokemons_bundle_id",
				Columns:    []*schema.Column{BundlePokemonsColumns[0]},
				RefColumns: []*schema.Column{BundlesColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "bundle_pokemons_pokemon_id",
				Columns:    []*schema.Column{BundlePokemonsColumns[1]},
				RefColumns: []*schema.Column{PokemonsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		BundlesTable,
		PokemonsTable,
		BundlePokemonsTable,
	}
)

func init() {
	BundlePokemonsTable.ForeignKeys[0].RefTable = BundlesTable
	BundlePokemonsTable.ForeignKeys[1].RefTable = PokemonsTable
}
