// Code generated by ent, DO NOT EDIT.

package pokemon

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the pokemon type in the database.
	Label = "pokemon"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUploadDatetime holds the string denoting the upload_datetime field in the database.
	FieldUploadDatetime = "upload_datetime"
	// FieldDownloadCode holds the string denoting the download_code field in the database.
	FieldDownloadCode = "download_code"
	// FieldDownloadCount holds the string denoting the download_count field in the database.
	FieldDownloadCount = "download_count"
	// FieldGeneration holds the string denoting the generation field in the database.
	FieldGeneration = "generation"
	// FieldLegal holds the string denoting the legal field in the database.
	FieldLegal = "legal"
	// FieldBase64 holds the string denoting the base_64 field in the database.
	FieldBase64 = "base_64"
	// EdgeBundles holds the string denoting the bundles edge name in mutations.
	EdgeBundles = "bundles"
	// Table holds the table name of the pokemon in the database.
	Table = "pokemons"
	// BundlesTable is the table that holds the bundles relation/edge. The primary key declared below.
	BundlesTable = "bundle_pokemons"
	// BundlesInverseTable is the table name for the Bundle entity.
	// It exists in this package in order to avoid circular dependency with the "bundle" package.
	BundlesInverseTable = "bundles"
)

// Columns holds all SQL columns for pokemon fields.
var Columns = []string{
	FieldID,
	FieldUploadDatetime,
	FieldDownloadCode,
	FieldDownloadCount,
	FieldGeneration,
	FieldLegal,
	FieldBase64,
}

var (
	// BundlesPrimaryKey and BundlesColumn2 are the table columns denoting the
	// primary key for the bundles relation (M2M).
	BundlesPrimaryKey = []string{"bundle_id", "pokemon_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Pokemon queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUploadDatetime orders the results by the upload_datetime field.
func ByUploadDatetime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUploadDatetime, opts...).ToFunc()
}

// ByDownloadCode orders the results by the download_code field.
func ByDownloadCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDownloadCode, opts...).ToFunc()
}

// ByDownloadCount orders the results by the download_count field.
func ByDownloadCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDownloadCount, opts...).ToFunc()
}

// ByGeneration orders the results by the generation field.
func ByGeneration(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGeneration, opts...).ToFunc()
}

// ByLegal orders the results by the legal field.
func ByLegal(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLegal, opts...).ToFunc()
}

// ByBase64 orders the results by the base_64 field.
func ByBase64(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBase64, opts...).ToFunc()
}

// ByBundlesCount orders the results by bundles count.
func ByBundlesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newBundlesStep(), opts...)
	}
}

// ByBundles orders the results by bundles terms.
func ByBundles(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newBundlesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newBundlesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(BundlesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, true, BundlesTable, BundlesPrimaryKey...),
	)
}
