// Code generated by ent, DO NOT EDIT.

package pokemon

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/FlagBrew/local-gpss/internal/database/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Pokemon {
	return predicate.Pokemon(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Pokemon {
	return predicate.Pokemon(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Pokemon {
	return predicate.Pokemon(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Pokemon {
	return predicate.Pokemon(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Pokemon {
	return predicate.Pokemon(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Pokemon {
	return predicate.Pokemon(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Pokemon {
	return predicate.Pokemon(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Pokemon {
	return predicate.Pokemon(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Pokemon {
	return predicate.Pokemon(sql.FieldLTE(FieldID, id))
}

// UploadDatetime applies equality check predicate on the "upload_datetime" field. It's identical to UploadDatetimeEQ.
func UploadDatetime(v time.Time) predicate.Pokemon {
	return predicate.Pokemon(sql.FieldEQ(FieldUploadDatetime, v))
}

// DownloadCode applies equality check predicate on the "download_code" field. It's identical to DownloadCodeEQ.
func DownloadCode(v string) predicate.Pokemon {
	return predicate.Pokemon(sql.FieldEQ(FieldDownloadCode, v))
}

// DownloadCount applies equality check predicate on the "download_count" field. It's identical to DownloadCountEQ.
func DownloadCount(v int) predicate.Pokemon {
	return predicate.Pokemon(sql.FieldEQ(FieldDownloadCount, v))
}

// Generation applies equality check predicate on the "generation" field. It's identical to GenerationEQ.
func Generation(v string) predicate.Pokemon {
	return predicate.Pokemon(sql.FieldEQ(FieldGeneration, v))
}

// Legal applies equality check predicate on the "legal" field. It's identical to LegalEQ.
func Legal(v bool) predicate.Pokemon {
	return predicate.Pokemon(sql.FieldEQ(FieldLegal, v))
}

// Base64 applies equality check predicate on the "base_64" field. It's identical to Base64EQ.
func Base64(v string) predicate.Pokemon {
	return predicate.Pokemon(sql.FieldEQ(FieldBase64, v))
}

// UploadDatetimeEQ applies the EQ predicate on the "upload_datetime" field.
func UploadDatetimeEQ(v time.Time) predicate.Pokemon {
	return predicate.Pokemon(sql.FieldEQ(FieldUploadDatetime, v))
}

// UploadDatetimeNEQ applies the NEQ predicate on the "upload_datetime" field.
func UploadDatetimeNEQ(v time.Time) predicate.Pokemon {
	return predicate.Pokemon(sql.FieldNEQ(FieldUploadDatetime, v))
}

// UploadDatetimeIn applies the In predicate on the "upload_datetime" field.
func UploadDatetimeIn(vs ...time.Time) predicate.Pokemon {
	return predicate.Pokemon(sql.FieldIn(FieldUploadDatetime, vs...))
}

// UploadDatetimeNotIn applies the NotIn predicate on the "upload_datetime" field.
func UploadDatetimeNotIn(vs ...time.Time) predicate.Pokemon {
	return predicate.Pokemon(sql.FieldNotIn(FieldUploadDatetime, vs...))
}

// UploadDatetimeGT applies the GT predicate on the "upload_datetime" field.
func UploadDatetimeGT(v time.Time) predicate.Pokemon {
	return predicate.Pokemon(sql.FieldGT(FieldUploadDatetime, v))
}

// UploadDatetimeGTE applies the GTE predicate on the "upload_datetime" field.
func UploadDatetimeGTE(v time.Time) predicate.Pokemon {
	return predicate.Pokemon(sql.FieldGTE(FieldUploadDatetime, v))
}

// UploadDatetimeLT applies the LT predicate on the "upload_datetime" field.
func UploadDatetimeLT(v time.Time) predicate.Pokemon {
	return predicate.Pokemon(sql.FieldLT(FieldUploadDatetime, v))
}

// UploadDatetimeLTE applies the LTE predicate on the "upload_datetime" field.
func UploadDatetimeLTE(v time.Time) predicate.Pokemon {
	return predicate.Pokemon(sql.FieldLTE(FieldUploadDatetime, v))
}

// DownloadCodeEQ applies the EQ predicate on the "download_code" field.
func DownloadCodeEQ(v string) predicate.Pokemon {
	return predicate.Pokemon(sql.FieldEQ(FieldDownloadCode, v))
}

// DownloadCodeNEQ applies the NEQ predicate on the "download_code" field.
func DownloadCodeNEQ(v string) predicate.Pokemon {
	return predicate.Pokemon(sql.FieldNEQ(FieldDownloadCode, v))
}

// DownloadCodeIn applies the In predicate on the "download_code" field.
func DownloadCodeIn(vs ...string) predicate.Pokemon {
	return predicate.Pokemon(sql.FieldIn(FieldDownloadCode, vs...))
}

// DownloadCodeNotIn applies the NotIn predicate on the "download_code" field.
func DownloadCodeNotIn(vs ...string) predicate.Pokemon {
	return predicate.Pokemon(sql.FieldNotIn(FieldDownloadCode, vs...))
}

// DownloadCodeGT applies the GT predicate on the "download_code" field.
func DownloadCodeGT(v string) predicate.Pokemon {
	return predicate.Pokemon(sql.FieldGT(FieldDownloadCode, v))
}

// DownloadCodeGTE applies the GTE predicate on the "download_code" field.
func DownloadCodeGTE(v string) predicate.Pokemon {
	return predicate.Pokemon(sql.FieldGTE(FieldDownloadCode, v))
}

// DownloadCodeLT applies the LT predicate on the "download_code" field.
func DownloadCodeLT(v string) predicate.Pokemon {
	return predicate.Pokemon(sql.FieldLT(FieldDownloadCode, v))
}

// DownloadCodeLTE applies the LTE predicate on the "download_code" field.
func DownloadCodeLTE(v string) predicate.Pokemon {
	return predicate.Pokemon(sql.FieldLTE(FieldDownloadCode, v))
}

// DownloadCodeContains applies the Contains predicate on the "download_code" field.
func DownloadCodeContains(v string) predicate.Pokemon {
	return predicate.Pokemon(sql.FieldContains(FieldDownloadCode, v))
}

// DownloadCodeHasPrefix applies the HasPrefix predicate on the "download_code" field.
func DownloadCodeHasPrefix(v string) predicate.Pokemon {
	return predicate.Pokemon(sql.FieldHasPrefix(FieldDownloadCode, v))
}

// DownloadCodeHasSuffix applies the HasSuffix predicate on the "download_code" field.
func DownloadCodeHasSuffix(v string) predicate.Pokemon {
	return predicate.Pokemon(sql.FieldHasSuffix(FieldDownloadCode, v))
}

// DownloadCodeEqualFold applies the EqualFold predicate on the "download_code" field.
func DownloadCodeEqualFold(v string) predicate.Pokemon {
	return predicate.Pokemon(sql.FieldEqualFold(FieldDownloadCode, v))
}

// DownloadCodeContainsFold applies the ContainsFold predicate on the "download_code" field.
func DownloadCodeContainsFold(v string) predicate.Pokemon {
	return predicate.Pokemon(sql.FieldContainsFold(FieldDownloadCode, v))
}

// DownloadCountEQ applies the EQ predicate on the "download_count" field.
func DownloadCountEQ(v int) predicate.Pokemon {
	return predicate.Pokemon(sql.FieldEQ(FieldDownloadCount, v))
}

// DownloadCountNEQ applies the NEQ predicate on the "download_count" field.
func DownloadCountNEQ(v int) predicate.Pokemon {
	return predicate.Pokemon(sql.FieldNEQ(FieldDownloadCount, v))
}

// DownloadCountIn applies the In predicate on the "download_count" field.
func DownloadCountIn(vs ...int) predicate.Pokemon {
	return predicate.Pokemon(sql.FieldIn(FieldDownloadCount, vs...))
}

// DownloadCountNotIn applies the NotIn predicate on the "download_count" field.
func DownloadCountNotIn(vs ...int) predicate.Pokemon {
	return predicate.Pokemon(sql.FieldNotIn(FieldDownloadCount, vs...))
}

// DownloadCountGT applies the GT predicate on the "download_count" field.
func DownloadCountGT(v int) predicate.Pokemon {
	return predicate.Pokemon(sql.FieldGT(FieldDownloadCount, v))
}

// DownloadCountGTE applies the GTE predicate on the "download_count" field.
func DownloadCountGTE(v int) predicate.Pokemon {
	return predicate.Pokemon(sql.FieldGTE(FieldDownloadCount, v))
}

// DownloadCountLT applies the LT predicate on the "download_count" field.
func DownloadCountLT(v int) predicate.Pokemon {
	return predicate.Pokemon(sql.FieldLT(FieldDownloadCount, v))
}

// DownloadCountLTE applies the LTE predicate on the "download_count" field.
func DownloadCountLTE(v int) predicate.Pokemon {
	return predicate.Pokemon(sql.FieldLTE(FieldDownloadCount, v))
}

// GenerationEQ applies the EQ predicate on the "generation" field.
func GenerationEQ(v string) predicate.Pokemon {
	return predicate.Pokemon(sql.FieldEQ(FieldGeneration, v))
}

// GenerationNEQ applies the NEQ predicate on the "generation" field.
func GenerationNEQ(v string) predicate.Pokemon {
	return predicate.Pokemon(sql.FieldNEQ(FieldGeneration, v))
}

// GenerationIn applies the In predicate on the "generation" field.
func GenerationIn(vs ...string) predicate.Pokemon {
	return predicate.Pokemon(sql.FieldIn(FieldGeneration, vs...))
}

// GenerationNotIn applies the NotIn predicate on the "generation" field.
func GenerationNotIn(vs ...string) predicate.Pokemon {
	return predicate.Pokemon(sql.FieldNotIn(FieldGeneration, vs...))
}

// GenerationGT applies the GT predicate on the "generation" field.
func GenerationGT(v string) predicate.Pokemon {
	return predicate.Pokemon(sql.FieldGT(FieldGeneration, v))
}

// GenerationGTE applies the GTE predicate on the "generation" field.
func GenerationGTE(v string) predicate.Pokemon {
	return predicate.Pokemon(sql.FieldGTE(FieldGeneration, v))
}

// GenerationLT applies the LT predicate on the "generation" field.
func GenerationLT(v string) predicate.Pokemon {
	return predicate.Pokemon(sql.FieldLT(FieldGeneration, v))
}

// GenerationLTE applies the LTE predicate on the "generation" field.
func GenerationLTE(v string) predicate.Pokemon {
	return predicate.Pokemon(sql.FieldLTE(FieldGeneration, v))
}

// GenerationContains applies the Contains predicate on the "generation" field.
func GenerationContains(v string) predicate.Pokemon {
	return predicate.Pokemon(sql.FieldContains(FieldGeneration, v))
}

// GenerationHasPrefix applies the HasPrefix predicate on the "generation" field.
func GenerationHasPrefix(v string) predicate.Pokemon {
	return predicate.Pokemon(sql.FieldHasPrefix(FieldGeneration, v))
}

// GenerationHasSuffix applies the HasSuffix predicate on the "generation" field.
func GenerationHasSuffix(v string) predicate.Pokemon {
	return predicate.Pokemon(sql.FieldHasSuffix(FieldGeneration, v))
}

// GenerationEqualFold applies the EqualFold predicate on the "generation" field.
func GenerationEqualFold(v string) predicate.Pokemon {
	return predicate.Pokemon(sql.FieldEqualFold(FieldGeneration, v))
}

// GenerationContainsFold applies the ContainsFold predicate on the "generation" field.
func GenerationContainsFold(v string) predicate.Pokemon {
	return predicate.Pokemon(sql.FieldContainsFold(FieldGeneration, v))
}

// LegalEQ applies the EQ predicate on the "legal" field.
func LegalEQ(v bool) predicate.Pokemon {
	return predicate.Pokemon(sql.FieldEQ(FieldLegal, v))
}

// LegalNEQ applies the NEQ predicate on the "legal" field.
func LegalNEQ(v bool) predicate.Pokemon {
	return predicate.Pokemon(sql.FieldNEQ(FieldLegal, v))
}

// Base64EQ applies the EQ predicate on the "base_64" field.
func Base64EQ(v string) predicate.Pokemon {
	return predicate.Pokemon(sql.FieldEQ(FieldBase64, v))
}

// Base64NEQ applies the NEQ predicate on the "base_64" field.
func Base64NEQ(v string) predicate.Pokemon {
	return predicate.Pokemon(sql.FieldNEQ(FieldBase64, v))
}

// Base64In applies the In predicate on the "base_64" field.
func Base64In(vs ...string) predicate.Pokemon {
	return predicate.Pokemon(sql.FieldIn(FieldBase64, vs...))
}

// Base64NotIn applies the NotIn predicate on the "base_64" field.
func Base64NotIn(vs ...string) predicate.Pokemon {
	return predicate.Pokemon(sql.FieldNotIn(FieldBase64, vs...))
}

// Base64GT applies the GT predicate on the "base_64" field.
func Base64GT(v string) predicate.Pokemon {
	return predicate.Pokemon(sql.FieldGT(FieldBase64, v))
}

// Base64GTE applies the GTE predicate on the "base_64" field.
func Base64GTE(v string) predicate.Pokemon {
	return predicate.Pokemon(sql.FieldGTE(FieldBase64, v))
}

// Base64LT applies the LT predicate on the "base_64" field.
func Base64LT(v string) predicate.Pokemon {
	return predicate.Pokemon(sql.FieldLT(FieldBase64, v))
}

// Base64LTE applies the LTE predicate on the "base_64" field.
func Base64LTE(v string) predicate.Pokemon {
	return predicate.Pokemon(sql.FieldLTE(FieldBase64, v))
}

// Base64Contains applies the Contains predicate on the "base_64" field.
func Base64Contains(v string) predicate.Pokemon {
	return predicate.Pokemon(sql.FieldContains(FieldBase64, v))
}

// Base64HasPrefix applies the HasPrefix predicate on the "base_64" field.
func Base64HasPrefix(v string) predicate.Pokemon {
	return predicate.Pokemon(sql.FieldHasPrefix(FieldBase64, v))
}

// Base64HasSuffix applies the HasSuffix predicate on the "base_64" field.
func Base64HasSuffix(v string) predicate.Pokemon {
	return predicate.Pokemon(sql.FieldHasSuffix(FieldBase64, v))
}

// Base64EqualFold applies the EqualFold predicate on the "base_64" field.
func Base64EqualFold(v string) predicate.Pokemon {
	return predicate.Pokemon(sql.FieldEqualFold(FieldBase64, v))
}

// Base64ContainsFold applies the ContainsFold predicate on the "base_64" field.
func Base64ContainsFold(v string) predicate.Pokemon {
	return predicate.Pokemon(sql.FieldContainsFold(FieldBase64, v))
}

// HasBundles applies the HasEdge predicate on the "bundles" edge.
func HasBundles() predicate.Pokemon {
	return predicate.Pokemon(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, BundlesTable, BundlesPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasBundlesWith applies the HasEdge predicate on the "bundles" edge with a given conditions (other predicates).
func HasBundlesWith(preds ...predicate.Bundle) predicate.Pokemon {
	return predicate.Pokemon(func(s *sql.Selector) {
		step := newBundlesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Pokemon) predicate.Pokemon {
	return predicate.Pokemon(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Pokemon) predicate.Pokemon {
	return predicate.Pokemon(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Pokemon) predicate.Pokemon {
	return predicate.Pokemon(sql.NotPredicates(p))
}
