// Code generated by ent, DO NOT EDIT.

package bundle

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the bundle type in the database.
	Label = "bundle"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUploadDatetime holds the string denoting the upload_datetime field in the database.
	FieldUploadDatetime = "upload_datetime"
	// FieldDownloadCode holds the string denoting the download_code field in the database.
	FieldDownloadCode = "download_code"
	// FieldDownloadCount holds the string denoting the download_count field in the database.
	FieldDownloadCount = "download_count"
	// FieldLegal holds the string denoting the legal field in the database.
	FieldLegal = "legal"
	// FieldMinGen holds the string denoting the min_gen field in the database.
	FieldMinGen = "min_gen"
	// FieldMaxGen holds the string denoting the max_gen field in the database.
	FieldMaxGen = "max_gen"
	// EdgePokemons holds the string denoting the pokemons edge name in mutations.
	EdgePokemons = "pokemons"
	// Table holds the table name of the bundle in the database.
	Table = "bundles"
	// PokemonsTable is the table that holds the pokemons relation/edge. The primary key declared below.
	PokemonsTable = "bundle_pokemons"
	// PokemonsInverseTable is the table name for the Pokemon entity.
	// It exists in this package in order to avoid circular dependency with the "pokemon" package.
	PokemonsInverseTable = "pokemons"
)

// Columns holds all SQL columns for bundle fields.
var Columns = []string{
	FieldID,
	FieldUploadDatetime,
	FieldDownloadCode,
	FieldDownloadCount,
	FieldLegal,
	FieldMinGen,
	FieldMaxGen,
}

var (
	// PokemonsPrimaryKey and PokemonsColumn2 are the table columns denoting the
	// primary key for the pokemons relation (M2M).
	PokemonsPrimaryKey = []string{"bundle_id", "pokemon_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Bundle queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUploadDatetime orders the results by the upload_datetime field.
func ByUploadDatetime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUploadDatetime, opts...).ToFunc()
}

// ByDownloadCode orders the results by the download_code field.
func ByDownloadCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDownloadCode, opts...).ToFunc()
}

// ByDownloadCount orders the results by the download_count field.
func ByDownloadCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDownloadCount, opts...).ToFunc()
}

// ByLegal orders the results by the legal field.
func ByLegal(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLegal, opts...).ToFunc()
}

// ByMinGen orders the results by the min_gen field.
func ByMinGen(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMinGen, opts...).ToFunc()
}

// ByMaxGen orders the results by the max_gen field.
func ByMaxGen(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaxGen, opts...).ToFunc()
}

// ByPokemonsCount orders the results by pokemons count.
func ByPokemonsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newPokemonsStep(), opts...)
	}
}

// ByPokemons orders the results by pokemons terms.
func ByPokemons(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPokemonsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newPokemonsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PokemonsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, false, PokemonsTable, PokemonsPrimaryKey...),
	)
}
