// Code generated by ent, DO NOT EDIT.

package bundle

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/FlagBrew/local-gpss/internal/database/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Bundle {
	return predicate.Bundle(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Bundle {
	return predicate.Bundle(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Bundle {
	return predicate.Bundle(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Bundle {
	return predicate.Bundle(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Bundle {
	return predicate.Bundle(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Bundle {
	return predicate.Bundle(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Bundle {
	return predicate.Bundle(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Bundle {
	return predicate.Bundle(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Bundle {
	return predicate.Bundle(sql.FieldLTE(FieldID, id))
}

// UploadDatetime applies equality check predicate on the "upload_datetime" field. It's identical to UploadDatetimeEQ.
func UploadDatetime(v time.Time) predicate.Bundle {
	return predicate.Bundle(sql.FieldEQ(FieldUploadDatetime, v))
}

// DownloadCode applies equality check predicate on the "download_code" field. It's identical to DownloadCodeEQ.
func DownloadCode(v string) predicate.Bundle {
	return predicate.Bundle(sql.FieldEQ(FieldDownloadCode, v))
}

// DownloadCount applies equality check predicate on the "download_count" field. It's identical to DownloadCountEQ.
func DownloadCount(v int) predicate.Bundle {
	return predicate.Bundle(sql.FieldEQ(FieldDownloadCount, v))
}

// Legal applies equality check predicate on the "legal" field. It's identical to LegalEQ.
func Legal(v bool) predicate.Bundle {
	return predicate.Bundle(sql.FieldEQ(FieldLegal, v))
}

// MinGen applies equality check predicate on the "min_gen" field. It's identical to MinGenEQ.
func MinGen(v string) predicate.Bundle {
	return predicate.Bundle(sql.FieldEQ(FieldMinGen, v))
}

// MaxGen applies equality check predicate on the "max_gen" field. It's identical to MaxGenEQ.
func MaxGen(v string) predicate.Bundle {
	return predicate.Bundle(sql.FieldEQ(FieldMaxGen, v))
}

// UploadDatetimeEQ applies the EQ predicate on the "upload_datetime" field.
func UploadDatetimeEQ(v time.Time) predicate.Bundle {
	return predicate.Bundle(sql.FieldEQ(FieldUploadDatetime, v))
}

// UploadDatetimeNEQ applies the NEQ predicate on the "upload_datetime" field.
func UploadDatetimeNEQ(v time.Time) predicate.Bundle {
	return predicate.Bundle(sql.FieldNEQ(FieldUploadDatetime, v))
}

// UploadDatetimeIn applies the In predicate on the "upload_datetime" field.
func UploadDatetimeIn(vs ...time.Time) predicate.Bundle {
	return predicate.Bundle(sql.FieldIn(FieldUploadDatetime, vs...))
}

// UploadDatetimeNotIn applies the NotIn predicate on the "upload_datetime" field.
func UploadDatetimeNotIn(vs ...time.Time) predicate.Bundle {
	return predicate.Bundle(sql.FieldNotIn(FieldUploadDatetime, vs...))
}

// UploadDatetimeGT applies the GT predicate on the "upload_datetime" field.
func UploadDatetimeGT(v time.Time) predicate.Bundle {
	return predicate.Bundle(sql.FieldGT(FieldUploadDatetime, v))
}

// UploadDatetimeGTE applies the GTE predicate on the "upload_datetime" field.
func UploadDatetimeGTE(v time.Time) predicate.Bundle {
	return predicate.Bundle(sql.FieldGTE(FieldUploadDatetime, v))
}

// UploadDatetimeLT applies the LT predicate on the "upload_datetime" field.
func UploadDatetimeLT(v time.Time) predicate.Bundle {
	return predicate.Bundle(sql.FieldLT(FieldUploadDatetime, v))
}

// UploadDatetimeLTE applies the LTE predicate on the "upload_datetime" field.
func UploadDatetimeLTE(v time.Time) predicate.Bundle {
	return predicate.Bundle(sql.FieldLTE(FieldUploadDatetime, v))
}

// DownloadCodeEQ applies the EQ predicate on the "download_code" field.
func DownloadCodeEQ(v string) predicate.Bundle {
	return predicate.Bundle(sql.FieldEQ(FieldDownloadCode, v))
}

// DownloadCodeNEQ applies the NEQ predicate on the "download_code" field.
func DownloadCodeNEQ(v string) predicate.Bundle {
	return predicate.Bundle(sql.FieldNEQ(FieldDownloadCode, v))
}

// DownloadCodeIn applies the In predicate on the "download_code" field.
func DownloadCodeIn(vs ...string) predicate.Bundle {
	return predicate.Bundle(sql.FieldIn(FieldDownloadCode, vs...))
}

// DownloadCodeNotIn applies the NotIn predicate on the "download_code" field.
func DownloadCodeNotIn(vs ...string) predicate.Bundle {
	return predicate.Bundle(sql.FieldNotIn(FieldDownloadCode, vs...))
}

// DownloadCodeGT applies the GT predicate on the "download_code" field.
func DownloadCodeGT(v string) predicate.Bundle {
	return predicate.Bundle(sql.FieldGT(FieldDownloadCode, v))
}

// DownloadCodeGTE applies the GTE predicate on the "download_code" field.
func DownloadCodeGTE(v string) predicate.Bundle {
	return predicate.Bundle(sql.FieldGTE(FieldDownloadCode, v))
}

// DownloadCodeLT applies the LT predicate on the "download_code" field.
func DownloadCodeLT(v string) predicate.Bundle {
	return predicate.Bundle(sql.FieldLT(FieldDownloadCode, v))
}

// DownloadCodeLTE applies the LTE predicate on the "download_code" field.
func DownloadCodeLTE(v string) predicate.Bundle {
	return predicate.Bundle(sql.FieldLTE(FieldDownloadCode, v))
}

// DownloadCodeContains applies the Contains predicate on the "download_code" field.
func DownloadCodeContains(v string) predicate.Bundle {
	return predicate.Bundle(sql.FieldContains(FieldDownloadCode, v))
}

// DownloadCodeHasPrefix applies the HasPrefix predicate on the "download_code" field.
func DownloadCodeHasPrefix(v string) predicate.Bundle {
	return predicate.Bundle(sql.FieldHasPrefix(FieldDownloadCode, v))
}

// DownloadCodeHasSuffix applies the HasSuffix predicate on the "download_code" field.
func DownloadCodeHasSuffix(v string) predicate.Bundle {
	return predicate.Bundle(sql.FieldHasSuffix(FieldDownloadCode, v))
}

// DownloadCodeEqualFold applies the EqualFold predicate on the "download_code" field.
func DownloadCodeEqualFold(v string) predicate.Bundle {
	return predicate.Bundle(sql.FieldEqualFold(FieldDownloadCode, v))
}

// DownloadCodeContainsFold applies the ContainsFold predicate on the "download_code" field.
func DownloadCodeContainsFold(v string) predicate.Bundle {
	return predicate.Bundle(sql.FieldContainsFold(FieldDownloadCode, v))
}

// DownloadCountEQ applies the EQ predicate on the "download_count" field.
func DownloadCountEQ(v int) predicate.Bundle {
	return predicate.Bundle(sql.FieldEQ(FieldDownloadCount, v))
}

// DownloadCountNEQ applies the NEQ predicate on the "download_count" field.
func DownloadCountNEQ(v int) predicate.Bundle {
	return predicate.Bundle(sql.FieldNEQ(FieldDownloadCount, v))
}

// DownloadCountIn applies the In predicate on the "download_count" field.
func DownloadCountIn(vs ...int) predicate.Bundle {
	return predicate.Bundle(sql.FieldIn(FieldDownloadCount, vs...))
}

// DownloadCountNotIn applies the NotIn predicate on the "download_count" field.
func DownloadCountNotIn(vs ...int) predicate.Bundle {
	return predicate.Bundle(sql.FieldNotIn(FieldDownloadCount, vs...))
}

// DownloadCountGT applies the GT predicate on the "download_count" field.
func DownloadCountGT(v int) predicate.Bundle {
	return predicate.Bundle(sql.FieldGT(FieldDownloadCount, v))
}

// DownloadCountGTE applies the GTE predicate on the "download_count" field.
func DownloadCountGTE(v int) predicate.Bundle {
	return predicate.Bundle(sql.FieldGTE(FieldDownloadCount, v))
}

// DownloadCountLT applies the LT predicate on the "download_count" field.
func DownloadCountLT(v int) predicate.Bundle {
	return predicate.Bundle(sql.FieldLT(FieldDownloadCount, v))
}

// DownloadCountLTE applies the LTE predicate on the "download_count" field.
func DownloadCountLTE(v int) predicate.Bundle {
	return predicate.Bundle(sql.FieldLTE(FieldDownloadCount, v))
}

// LegalEQ applies the EQ predicate on the "legal" field.
func LegalEQ(v bool) predicate.Bundle {
	return predicate.Bundle(sql.FieldEQ(FieldLegal, v))
}

// LegalNEQ applies the NEQ predicate on the "legal" field.
func LegalNEQ(v bool) predicate.Bundle {
	return predicate.Bundle(sql.FieldNEQ(FieldLegal, v))
}

// MinGenEQ applies the EQ predicate on the "min_gen" field.
func MinGenEQ(v string) predicate.Bundle {
	return predicate.Bundle(sql.FieldEQ(FieldMinGen, v))
}

// MinGenNEQ applies the NEQ predicate on the "min_gen" field.
func MinGenNEQ(v string) predicate.Bundle {
	return predicate.Bundle(sql.FieldNEQ(FieldMinGen, v))
}

// MinGenIn applies the In predicate on the "min_gen" field.
func MinGenIn(vs ...string) predicate.Bundle {
	return predicate.Bundle(sql.FieldIn(FieldMinGen, vs...))
}

// MinGenNotIn applies the NotIn predicate on the "min_gen" field.
func MinGenNotIn(vs ...string) predicate.Bundle {
	return predicate.Bundle(sql.FieldNotIn(FieldMinGen, vs...))
}

// MinGenGT applies the GT predicate on the "min_gen" field.
func MinGenGT(v string) predicate.Bundle {
	return predicate.Bundle(sql.FieldGT(FieldMinGen, v))
}

// MinGenGTE applies the GTE predicate on the "min_gen" field.
func MinGenGTE(v string) predicate.Bundle {
	return predicate.Bundle(sql.FieldGTE(FieldMinGen, v))
}

// MinGenLT applies the LT predicate on the "min_gen" field.
func MinGenLT(v string) predicate.Bundle {
	return predicate.Bundle(sql.FieldLT(FieldMinGen, v))
}

// MinGenLTE applies the LTE predicate on the "min_gen" field.
func MinGenLTE(v string) predicate.Bundle {
	return predicate.Bundle(sql.FieldLTE(FieldMinGen, v))
}

// MinGenContains applies the Contains predicate on the "min_gen" field.
func MinGenContains(v string) predicate.Bundle {
	return predicate.Bundle(sql.FieldContains(FieldMinGen, v))
}

// MinGenHasPrefix applies the HasPrefix predicate on the "min_gen" field.
func MinGenHasPrefix(v string) predicate.Bundle {
	return predicate.Bundle(sql.FieldHasPrefix(FieldMinGen, v))
}

// MinGenHasSuffix applies the HasSuffix predicate on the "min_gen" field.
func MinGenHasSuffix(v string) predicate.Bundle {
	return predicate.Bundle(sql.FieldHasSuffix(FieldMinGen, v))
}

// MinGenEqualFold applies the EqualFold predicate on the "min_gen" field.
func MinGenEqualFold(v string) predicate.Bundle {
	return predicate.Bundle(sql.FieldEqualFold(FieldMinGen, v))
}

// MinGenContainsFold applies the ContainsFold predicate on the "min_gen" field.
func MinGenContainsFold(v string) predicate.Bundle {
	return predicate.Bundle(sql.FieldContainsFold(FieldMinGen, v))
}

// MaxGenEQ applies the EQ predicate on the "max_gen" field.
func MaxGenEQ(v string) predicate.Bundle {
	return predicate.Bundle(sql.FieldEQ(FieldMaxGen, v))
}

// MaxGenNEQ applies the NEQ predicate on the "max_gen" field.
func MaxGenNEQ(v string) predicate.Bundle {
	return predicate.Bundle(sql.FieldNEQ(FieldMaxGen, v))
}

// MaxGenIn applies the In predicate on the "max_gen" field.
func MaxGenIn(vs ...string) predicate.Bundle {
	return predicate.Bundle(sql.FieldIn(FieldMaxGen, vs...))
}

// MaxGenNotIn applies the NotIn predicate on the "max_gen" field.
func MaxGenNotIn(vs ...string) predicate.Bundle {
	return predicate.Bundle(sql.FieldNotIn(FieldMaxGen, vs...))
}

// MaxGenGT applies the GT predicate on the "max_gen" field.
func MaxGenGT(v string) predicate.Bundle {
	return predicate.Bundle(sql.FieldGT(FieldMaxGen, v))
}

// MaxGenGTE applies the GTE predicate on the "max_gen" field.
func MaxGenGTE(v string) predicate.Bundle {
	return predicate.Bundle(sql.FieldGTE(FieldMaxGen, v))
}

// MaxGenLT applies the LT predicate on the "max_gen" field.
func MaxGenLT(v string) predicate.Bundle {
	return predicate.Bundle(sql.FieldLT(FieldMaxGen, v))
}

// MaxGenLTE applies the LTE predicate on the "max_gen" field.
func MaxGenLTE(v string) predicate.Bundle {
	return predicate.Bundle(sql.FieldLTE(FieldMaxGen, v))
}

// MaxGenContains applies the Contains predicate on the "max_gen" field.
func MaxGenContains(v string) predicate.Bundle {
	return predicate.Bundle(sql.FieldContains(FieldMaxGen, v))
}

// MaxGenHasPrefix applies the HasPrefix predicate on the "max_gen" field.
func MaxGenHasPrefix(v string) predicate.Bundle {
	return predicate.Bundle(sql.FieldHasPrefix(FieldMaxGen, v))
}

// MaxGenHasSuffix applies the HasSuffix predicate on the "max_gen" field.
func MaxGenHasSuffix(v string) predicate.Bundle {
	return predicate.Bundle(sql.FieldHasSuffix(FieldMaxGen, v))
}

// MaxGenEqualFold applies the EqualFold predicate on the "max_gen" field.
func MaxGenEqualFold(v string) predicate.Bundle {
	return predicate.Bundle(sql.FieldEqualFold(FieldMaxGen, v))
}

// MaxGenContainsFold applies the ContainsFold predicate on the "max_gen" field.
func MaxGenContainsFold(v string) predicate.Bundle {
	return predicate.Bundle(sql.FieldContainsFold(FieldMaxGen, v))
}

// HasPokemons applies the HasEdge predicate on the "pokemons" edge.
func HasPokemons() predicate.Bundle {
	return predicate.Bundle(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, PokemonsTable, PokemonsPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPokemonsWith applies the HasEdge predicate on the "pokemons" edge with a given conditions (other predicates).
func HasPokemonsWith(preds ...predicate.Pokemon) predicate.Bundle {
	return predicate.Bundle(func(s *sql.Selector) {
		step := newPokemonsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Bundle) predicate.Bundle {
	return predicate.Bundle(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Bundle) predicate.Bundle {
	return predicate.Bundle(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Bundle) predicate.Bundle {
	return predicate.Bundle(sql.NotPredicates(p))
}
